window.LESSONS = [
    {
        "id":  "L01",
        "title":  "语法地图开营",
        "markdown":  "### LessonMeta\n- 目标：认识词类；理解句子最小结构；知道本课程闯关规则。\n- 预备知识：会读简单单词和句子。\n- 学习产出：能把一句话拆成“谁 + 做什么 + 什么”。\n\n### WarmupScene\n- 图：语法岛地图，5个区域分别是“句子镇、名词港、时态城、比较山、连接桥”。\n- 对话：\n1. A: What is grammar?  \n2. B: Grammar is the rule of good sentences.  \n3. A: Can we learn grammar by games?  \n4. B: Yes, let’s start the adventure!\n\n### RuleCard\n1. 句子至少要有“主语 + 谓语”。  \nExample: I run.\n2. 词有不同工作：名词、动词、形容词、代词等。  \nExample: The small dog runs fast.\n3. 语法不是背定义，而是“在语境里用对句子”。\n\n### PitfallBox\n- 错：Run in the park.（无主语）  \n  对：I run in the park.\n- 错：my name is Tom.  \n  对：My name is Tom.\n\n### PracticeA（5）\n1. 圈出主语：`Tom plays football.`  \n2. 圈出动词：`My sister sings well.`  \n3. 补全主语：`___ is my friend.`  \n4. 判断是否是完整句：`In the classroom.`  \n5. 改正大小写：`we are happy.`\n\n### PracticeB（3）\n1. 把词连成句：`play / I / basketball`  \n2. 读句子并标注词类：`The cat is cute.`  \n3. 用“主语+谓语”写1句介绍自己。\n\n### PracticeC（2）\n1. 给图片“公园晨跑”写2句完整句。  \n2. 判断并改错：`Is rainy today.`\n\n### FunMission\n- 任务：语法岛入门卡。把10个词贴到“名词/动词/形容词”三栏。\n\n### ExitTicket\n1. 句子最少需要哪两个部分？  \n2. 在 `Lucy reads books.` 中，哪个是谓语？  \n3. `my dog is black.` 怎么改？  \n- 自评徽章：`Grammar Explorer`\n\n---"
    },
    {
        "id":  "L02",
        "title":  "句子零件工厂",
        "markdown":  "### LessonMeta\n- 目标：掌握主语/谓语/宾语；规范大小写和标点。\n- 预备知识：L01。\n- 学习产出：能拼装并改写基本陈述句。\n\n### WarmupScene\n- 图：机器人句子工厂，零件箱标有 S / V / O。\n- 对话：\n1. A: What does S-V-O mean?  \n2. B: Subject, Verb, Object.  \n3. A: Can every sentence use S-V-O?  \n4. B: Many sentences can.\n\n### RuleCard\n1. 常见句型：S + V + O。  \nExample: We love English.\n2. 句首字母大写，句末用 `.` `?` `!`。  \n3. 人称代词 `I` 永远大写。\n\n### PitfallBox\n- 错：i like apples  \n  对：I like apples.\n- 错：She is a doctor?（陈述句误用问号）  \n  对：She is a doctor.\n\n### PracticeA（5）\n1. 标注S/V/O：`They watch TV.`  \n2. 改正：`he play football.`  \n3. 选标点：`What is your name__`  \n4. 补全宾语：`I read ___.`  \n5. 改为完整句：`My brother in Grade 6.`\n\n### PracticeB（3）\n1. 用 `S+V+O` 写2句校园生活。  \n2. 找错并改：`we are classmates!`  \n3. 将 `She likes music.` 改成否定句。\n\n### PracticeC（2）\n1. 看图（操场）写3句，至少1句用 `!`。  \n2. 句子重排：`in / studies / Lucy / the library`\n\n### FunMission\n- 任务：句子拼装赛。小组抽3张词卡，60秒拼出正确句。\n\n### ExitTicket\n1. `I` 什么时候要大写？  \n2. `Tom eats lunch.` 的宾语是什么？  \n3. `she is happy` 如何规范书写？  \n- 自评徽章：`Sentence Builder`\n\n---"
    },
    {
        "id":  "L03",
        "title":  "名词特工队",
        "markdown":  "### LessonMeta\n- 目标：区分可数/不可数名词；掌握常见复数变化。\n- 预备知识：L01-L02。\n- 学习产出：能根据数量正确选择名词形式。\n\n### WarmupScene\n- 图：超市货架，一边是 apples/books，另一边是 milk/rice。\n- 对话：\n1. A: How many apples do you want?  \n2. B: Three apples, please.  \n3. A: How much milk do you want?  \n4. B: A little milk.\n\n### RuleCard\n1. 可数名词可数数量，有单复数。  \nExample: one book / two books\n2. 不可数名词一般无复数。  \nExample: water, milk, rice\n3. 复数常见变化：`-s/-es`，特殊：`child-children`、`man-men`。\n\n### PitfallBox\n- 错：two bread  \n  对：two pieces of bread\n- 错：three childs  \n  对：three children\n\n### PracticeA（5）\n1. 写复数：`bus, box, baby`  \n2. 判断可数/不可数：`juice, pen, rice`  \n3. 选词：`How many/how much` water?  \n4. 改错：`two milks`  \n5. 填空：`There are five ___ (tomato).`\n\n### PracticeB（3）\n1. 设计购物单：5个可数+3个不可数。  \n2. 用 `How many` 和 `How much` 各写1问1答。  \n3. 改写：`I have a child.` -\u003e 复数句。\n\n### PracticeC（2）\n1. 看图（冰箱）写4句数量表达。  \n2. 完成分类表：把12个名词分到可数/不可数。\n\n### FunMission\n- 任务：超市采购挑战。预算50元，写英语采购清单并口头汇报。\n\n### ExitTicket\n1. `information` 是可数还是不可数？  \n2. `knife` 的复数如何写？  \n3. `How much apples...?` 为什么错？  \n- 自评徽章：`Noun Agent`\n\n---"
    },
    {
        "id":  "L04",
        "title":  "冠词与数量词",
        "markdown":  "### LessonMeta\n- 目标：掌握 a/an/the 与 some/any/many/much 的用法。\n- 预备知识：L03。\n- 学习产出：能在句子中正确选冠词和数量词。\n\n### WarmupScene\n- 图：早餐桌上有 egg, apple, bread, milk。\n- 对话：\n1. A: I want an egg and an apple.  \n2. B: Do you want any milk?  \n3. A: Yes, I need some milk.  \n4. B: Great, here is the milk.\n\n### RuleCard\n1. `a/an` 表示“一个”，`an` 用于元音音素开头词。  \n2. `the` 表示特指（双方都知道的那个）。  \n3. `some` 常用于肯定句，`any` 常用于否定/疑问句；`many+可数复数`，`much+不可数`。\n\n### PitfallBox\n- 错：a apple  \n  对：an apple\n- 错：much books  \n  对：many books\n\n### PracticeA（5）\n1. 选冠词：`__ orange, __ university, __ sun`  \n2. some/any 填空：`Do you have ___ pencils?`  \n3. many/much 填空：`How ___ water?`  \n4. 改错：`I need any help.`  \n5. 选词：`This is ___ book on the desk.`\n\n### PracticeB（3）\n1. 写3句：各用 a/an/the。  \n2. 看图写2个 some/any 问答句。  \n3. 改写：`I have books.` -\u003e 用 many。\n\n### PracticeC（2）\n1. 早餐点单对话补全（8空）。  \n2. 阅读短文，圈出所有冠词并说明作用。\n\n### FunMission\n- 任务：食物篮配对赛。把词卡放进正确篮子：`a/an/the/some/any`。\n\n### ExitTicket\n1. 为什么是 `an hour`？  \n2. `the` 和 `a` 最大区别是什么？  \n3. `many milk` 如何改？  \n- 自评徽章：`Article Master`\n\n---"
    },
    {
        "id":  "L05",
        "title":  "代词换装秀",
        "markdown":  "### LessonMeta\n- 目标：掌握主格、宾格、形容词性物主代词、名词性物主代词。\n- 预备知识：L02。\n- 学习产出：能避免重复名词并正确替换。\n\n### WarmupScene\n- 图：三位同学交换文具。\n- 对话：\n1. A: This is my pen.  \n2. B: Is it yours?  \n3. C: We like her bag.  \n4. A: She gives it to us.\n\n### RuleCard\n1. 主格作主语：I, you, he, she, it, we, they。  \n2. 宾格作宾语：me, you, him, her, it, us, them。  \n3. 物主代词：`my/your...` + 名词；`mine/yours...` 可单独使用。\n\n### PitfallBox\n- 错：Me am a student.  \n  对：I am a student.\n- 错：This is my.  \n  对：This is mine.\n\n### PracticeA（5）\n1. 选主格/宾格：`___ (He/Him) likes me.`  \n2. 填空：`This is ___ (my/mine) book.`  \n3. 改写：`The bike is Tom\u0027s.` -\u003e `The bike is ___ .`  \n4. 改错：`Her is my friend.`  \n5. 选词：`Please help ___ (I/me).`\n\n### PracticeB（3）\n1. 用 `I/me/my/mine` 各写1句。  \n2. 两人对话：借文具，至少用4个代词。  \n3. 把重复名词改为代词：`Lucy likes Lucy\u0027s dog.`\n\n### PracticeC（2）\n1. 阅读短文，替换10处重复名词为代词。  \n2. 纠错题（6句）中找出代词错误并改正。\n\n### FunMission\n- 任务：角色替换卡。抽“人物卡+动作卡”，把名词句瞬间改成代词句。\n\n### ExitTicket\n1. `She helps ___ (we/us).` 选哪个？  \n2. `This ruler is ___ (my/mine).` 选哪个？  \n3. `Them are in the room.` 如何改？  \n- 自评徽章：`Pronoun Stylist`\n\n---"
    },
    {
        "id":  "L06",
        "title":  "Be动词指挥官",
        "markdown":  "### LessonMeta\n- 目标：掌握 am/is/are 的选择及肯否疑变换。\n- 预备知识：代词。\n- 学习产出：能熟练完成 be 句三种句型转换。\n\n### WarmupScene\n- 图：班级点名场景。\n- 对话：\n1. A: I am here.  \n2. B: She is not late.  \n3. C: Are they in the classroom?  \n4. D: Yes, they are.\n\n### RuleCard\n1. `I am`，`he/she/it is`，`you/we/they are`。  \n2. 否定句：be 后加 not。  \n3. 一般疑问句：be 提前，回答用 `Yes/No + 主语 + be`。\n\n### PitfallBox\n- 错：He are a boy.  \n  对：He is a boy.\n- 错：Are she happy?  \n  对：Is she happy?\n\n### PracticeA（5）\n1. 填空：`I ___ happy.`  \n2. 变否定：`They are ready.`  \n3. 变疑问：`She is at home.`  \n4. 回答：`Are you a student?`  \n5. 改错：`We is friends.`\n\n### PracticeB（3）\n1. 看图写3个be句（肯/否/疑各1）。  \n2. 对话补全（am/is/are）。  \n3. 造句：用 `there` + be（预热L07）。\n\n### PracticeC（2）\n1. 把短文中8个be动词改正确。  \n2. 抢答：老师读主语，你快速说 be 形式。\n\n### FunMission\n- 任务：错句急救站。3分钟抢救10个错误 be 句。\n\n### ExitTicket\n1. `I` 搭配哪个 be？  \n2. `He is tall.` 的疑问句是什么？  \n3. `They am not here.` 如何改？  \n- 自评徽章：`Be Commander`\n\n---"
    },
    {
        "id":  "L07",
        "title":  "There be空间站",
        "markdown":  "### LessonMeta\n- 目标：掌握 there is/there are，会描述位置。\n- 预备知识：be动词、名词单复数。\n- 学习产出：能准确表达“某地有某物”。\n\n### WarmupScene\n- 图：卧室俯视图（bed, desk, books, lamp）。\n- 对话：\n1. A: There is a bed in my room.  \n2. B: There are two books on the desk.  \n3. A: Is there a lamp near the bed?  \n4. B: Yes, there is.\n\n### RuleCard\n1. `There is + 单数/不可数`；`There are + 复数`。  \n2. 地点介词常见：in/on/under/near。  \n3. 疑问句：`Is/Are there ...?`\n\n### PitfallBox\n- 错：There are a cat on the chair.  \n  对：There is a cat on the chair.\n- 错：There is two pens.  \n  对：There are two pens.\n\n### PracticeA（5）\n1. is/are 填空（5句）。  \n2. 看图填地点介词。  \n3. 改错：`Are there a book?`  \n4. 变否定：`There is some juice.`  \n5. 变疑问：`There are three boys.`\n\n### PracticeB（3）\n1. 描述你的书包（至少3句 there be）。  \n2. 两图找不同，用 there be 写2句。  \n3. 与 L06 对比：`There is` vs `It is`。\n\n### PracticeC（2）\n1. 完成“我的梦想教室”描述短文（8空）。  \n2. 听描述，画出物品位置（可口头）。\n\n### FunMission\n- 任务：房间寻宝图。根据英文线索找5个物品并写句子。\n\n### ExitTicket\n1. `There ___ some water.` 填什么？  \n2. `There are a dog...` 错在哪？  \n3. 用 there be 造1句关于教室的话。  \n- 自评徽章：`Space Reporter`\n\n---"
    },
    {
        "id":  "L08",
        "title":  "一般现在时",
        "markdown":  "### LessonMeta\n- 目标：掌握一般现在时陈述习惯；掌握三单变化。\n- 预备知识：动词基础。\n- 学习产出：能写“日常作息”短段落。\n\n### WarmupScene\n- 图：时间轴（get up, go to school, do homework）。\n- 对话：\n1. A: I get up at 6:30 every day.  \n2. B: My brother goes to school at 7:10.  \n3. A: Does he like school?  \n4. B: Yes, he does.\n\n### RuleCard\n1. 表示习惯或事实，用一般现在时。  \n2. 主语三单（he/she/it）时，动词常加 `-s/-es`。  \n3. 否定/疑问常用 `do/does`。\n\n### PitfallBox\n- 错：He go to school by bus.  \n  对：He goes to school by bus.\n- 错：Does she likes music?  \n  对：Does she like music?\n\n### PracticeA（5）\n1. 动词三单：`watch, study, play`  \n2. 改否定：`Tom likes milk.`  \n3. 改疑问：`They play tennis.`  \n4. 频率副词填空：always/often/sometimes/never  \n5. 改错：`My father don\u0027t cook.`\n\n### PracticeB（3）\n1. 写“我的一天”5句，至少2句三单。  \n2. 两人互问作息，完成问卷。  \n3. 阅读短文找出所有一般现在时动词。\n\n### PracticeC（2）\n1. 句型转换综合（6小题）。  \n2. 写一段“我的好朋友”并标注三单动词。\n\n### FunMission\n- 任务：日常时间轴挑战。把打乱的活动按时间排序并写句。\n\n### ExitTicket\n1. 三单动词为什么变？  \n2. `He doesn\u0027t ___ (like/likes) PE.`  \n3. 写1句带 `often` 的一般现在时。  \n- 自评徽章：`Daily Routine Pro`\n\n---"
    },
    {
        "id":  "L09",
        "title":  "现在进行时",
        "markdown":  "### LessonMeta\n- 目标：掌握 be + V-ing；识别现在进行时提示词。\n- 预备知识：be动词、动词原形。\n- 学习产出：能描述“此刻正在发生”的动作。\n\n### WarmupScene\n- 图：直播画面，多个学生在做不同动作。\n- 对话：\n1. A: Look! Tom is running.  \n2. B: Lucy is reading now.  \n3. A: Are they playing basketball?  \n4. B: No, they aren’t.\n\n### RuleCard\n1. 结构：`am/is/are + V-ing`。  \n2. 常见提示词：now, look, listen, at the moment。  \n3. 一般疑问句：be 提前。\n\n### PitfallBox\n- 错：She reading now.  \n  对：She is reading now.\n- 错：They are play football.  \n  对：They are playing football.\n\n### PracticeA（5）\n1. 动词改 ing：`swim, make, write`  \n2. 选时态：now / every day。  \n3. 改否定：`I am drawing.`  \n4. 改疑问：`He is singing.`  \n5. 改错：`Are you do homework?`\n\n### PracticeB（3）\n1. 看图写4句进行时。  \n2. 与一般现在时对比填空（6空）。  \n3. 两人对话：电话里问“你在做什么”。\n\n### PracticeC（2）\n1. “教室直播”配音：给6张图各写1句。  \n2. 阅读短文，圈出非进行时并改正。\n\n### FunMission\n- 任务：直播间解说员。30秒连续用进行时口播画面。\n\n### ExitTicket\n1. 现在进行时的核心结构是什么？  \n2. `Look! It ___ (rain).`  \n3. `He is play.` 如何改？  \n- 自评徽章：`Live Commentator`\n\n---"
    },
    {
        "id":  "L10",
        "title":  "一般过去时①（规则动词）",
        "markdown":  "### LessonMeta\n- 目标：掌握规则过去式；理解过去时间状语。\n- 预备知识：一般现在时。\n- 学习产出：能写“昨天发生了什么”。\n\n### WarmupScene\n- 图：昨天的校园活动照片墙。\n- 对话：\n1. A: What did you do yesterday?  \n2. B: I played football and watched TV.  \n3. A: Did you finish your homework?  \n4. B: Yes, I did.\n\n### RuleCard\n1. 一般过去时表示过去发生的动作。  \n2. 规则动词常加 `-ed`（play-played, watch-watched）。  \n3. 否定/疑问常用 `did/didn\u0027t`，后接动词原形。\n\n### PitfallBox\n- 错：I didn\u0027t went to school.  \n  对：I didn\u0027t go to school.\n- 错：Did he played basketball?  \n  对：Did he play basketball?\n\n### PracticeA（5）\n1. 写过去式：`clean, dance, stop`  \n2. 选时间词：yesterday/now/tomorrow  \n3. 改否定：`She visited her grandma.`  \n4. 改疑问：`They watched a film.`  \n5. 改错：`We goed home early.`\n\n### PracticeB（3）\n1. 完成“我的昨天”4句。  \n2. 问答配对：`Did you...?`  \n3. 读短文找出过去时动词。\n\n### PracticeC（2）\n1. 写“上周末小日记”（5句）。  \n2. 句型混合改写（肯/否/疑）。\n\n### FunMission\n- 任务：昨日新闻播报。每组写3条“Yesterday News”并播报。\n\n### ExitTicket\n1. `did` 后面动词用什么形式？  \n2. `I ___ (visit) my uncle yesterday.`  \n3. `Did she went...?` 如何改？  \n- 自评徽章：`Past Reporter`\n\n---"
    },
    {
        "id":  "L11",
        "title":  "一般过去时②（不规则动词）",
        "markdown":  "### LessonMeta\n- 目标：掌握常见不规则过去式；强化 did 句型转换。\n- 预备知识：L10。\n- 学习产出：能在问答中正确使用过去式。\n\n### WarmupScene\n- 图：周末活动卡片（go, eat, see, buy）。\n- 对话：\n1. A: Where did you go last Sunday?  \n2. B: I went to the zoo.  \n3. A: What did you eat there?  \n4. B: I ate a hot dog.\n\n### RuleCard\n1. 常见不规则：go-went, eat-ate, see-saw, buy-bought, have-had。  \n2. 过去时问句：`Did + 主语 + 动词原形 ...?`  \n3. 回答：`Yes, ... did.` / `No, ... didn\u0027t.`\n\n### PitfallBox\n- 错：I goed to the park.  \n  对：I went to the park.\n- 错：What did you ate?  \n  对：What did you eat?\n\n### PracticeA（5）\n1. 配对不规则动词原形与过去式。  \n2. 填空：`She ___ (have) a cold yesterday.`  \n3. 改问句：`He saw a bird.`  \n4. 回答：`Did they buy books?`  \n5. 改错：`We didn\u0027t saw him.`\n\n### PracticeB（3）\n1. 采访同桌：昨天做了什么（3问3答）。  \n2. 用 `went/ate/saw` 各写1句。  \n3. 短文改错（4处）。\n\n### PracticeC（2）\n1. 记忆翻牌：20个不规则动词快配。  \n2. 写“上次春游”6句，至少3个不规则动词。\n\n### FunMission\n- 任务：记忆翻牌PK。限时记住并说出过去式。\n\n### ExitTicket\n1. `go` 的过去式是什么？  \n2. `Did he ___ (saw/see) it?`  \n3. `I didn\u0027t went.` 如何改？  \n- 自评徽章：`Time Traveler`\n\n---"
    },
    {
        "id":  "L12",
        "title":  "一般将来时",
        "markdown":  "### LessonMeta\n- 目标：掌握 be going to 与 will 的基础用法。\n- 预备知识：一般现在/过去时。\n- 学习产出：能表达计划与简单预测。\n\n### WarmupScene\n- 图：周末计划板（picnic, movie, homework）。\n- 对话：\n1. A: What are you going to do this weekend?  \n2. B: I am going to visit my grandparents.  \n3. A: Will it rain tomorrow?  \n4. B: I think it will.\n\n### RuleCard\n1. `be going to` 常表示已有计划。  \n2. `will` 常表示临时决定或预测。  \n3. 将来时间词：tomorrow, next week, soon。\n\n### PitfallBox\n- 错：I going to play football.  \n  对：I am going to play football.\n- 错：Will you to come?  \n  对：Will you come?\n\n### PracticeA（5）\n1. 填 be：`She ___ going to read.`  \n2. will/be going to 选择（5句）。  \n3. 改否定：`They will win.`  \n4. 改疑问：`You are going to swim.`  \n5. 改错：`He will goes home.`\n\n### PracticeB（3）\n1. 写3个周末计划句。  \n2. 预测明天天气2句。  \n3. 对话补全（8空）。\n\n### PracticeC（2）\n1. 设计“假期计划海报”英文文案（5句）。  \n2. 综合选择题（时态混合）。\n\n### FunMission\n- 任务：周末计划师。和同伴互相提问并做计划表。\n\n### ExitTicket\n1. `will` 后接动词什么形式？  \n2. `I ___ going to clean my room.`  \n3. `Will she plays...?` 如何改？  \n- 自评徽章：`Future Planner`\n\n---"
    },
    {
        "id":  "L13",
        "title":  "时态对比总练",
        "markdown":  "### LessonMeta\n- 目标：辨析一般现在、现在进行、一般过去、一般将来。\n- 预备知识：L08-L12。\n- 学习产出：能按时间线选择正确时态。\n\n### WarmupScene\n- 图：时光隧道（past-now-future）。\n- 对话：\n1. A: I play basketball every day.  \n2. B: I am playing now.  \n3. A: I played yesterday.  \n4. B: I will play tomorrow.\n\n### RuleCard\n1. 先看时间词，再选时态。  \n2. 进行时看“正在发生”；一般现在看“习惯事实”。  \n3. 过去与将来要注意动词形式变化。\n\n### PitfallBox\n- 错：Yesterday I play football.  \n  对：Yesterday I played football.\n- 错：Now he plays the piano.  \n  对：Now he is playing the piano.\n\n### PracticeA（5）\n1. 时间词配时态（5组）。  \n2. 动词正确形式填空（8空）。  \n3. 找出句子时态并标记。  \n4. 改错（4句）。  \n5. 快速分类：10句放入4种时态。\n\n### PracticeB（3）\n1. 写“昨天-今天-明天”各2句。  \n2. 阅读短文，完成时态选择。  \n3. 口头问答：老师给时间词，你造句。\n\n### PracticeC（2）\n1. 时光隧道挑战卷（10题综合）。  \n2. 写小段落《My Busy Weekend》（含3种时态）。\n\n### FunMission\n- 任务：时光隧道选择题闯关，答对解锁下一关。\n\n### ExitTicket\n1. `now` 常对应哪种时态？  \n2. `last week` 常对应哪种时态？  \n3. 写1句将来时。  \n- 自评徽章：`Tense Detective`\n\n---"
    },
    {
        "id":  "L14",
        "title":  "情态动词入门",
        "markdown":  "### LessonMeta\n- 目标：掌握 can/can\u0027t, must/mustn\u0027t, should 的基本语义。\n- 预备知识：基础句子结构。\n- 学习产出：能表达能力、规则与建议。\n\n### WarmupScene\n- 图：校园规则海报。\n- 对话：\n1. A: Can you swim?  \n2. B: Yes, I can.  \n3. A: Must we run in the hall?  \n4. B: No, we mustn\u0027t.\n\n### RuleCard\n1. `can` 表能力；`can\u0027t` 表不能。  \n2. `must` 表必须；`mustn\u0027t` 表禁止。  \n3. `should` 表建议，语气较温和。\n\n### PitfallBox\n- 错：He can swims.  \n  对：He can swim.\n- 错：You mustn\u0027t to eat here.  \n  对：You mustn\u0027t eat here.\n\n### PracticeA（5）\n1. can/can\u0027t 填空（5句）。  \n2. must/mustn\u0027t 选词（校园规则）。  \n3. should 造句（健康建议）。  \n4. 改错：`She can sings.`  \n5. 回答：`Can you ride a bike?`\n\n### PracticeB（3）\n1. 写3条班级规则（must/mustn\u0027t）。  \n2. 给朋友3条建议（should）。  \n3. 对话补全（6空）。\n\n### PracticeC（2）\n1. 情景写作：`At the library`（4句）。  \n2. 抢答：听情景选情态动词。\n\n### FunMission\n- 任务：校园规则法官。判断行为是否合规并给出句子。\n\n### ExitTicket\n1. 情态动词后面动词用什么形式？  \n2. `You ___ be quiet in class.`  \n3. `He can to swim.` 如何改？  \n- 自评徽章：`Rule Keeper`\n\n---"
    },
    {
        "id":  "L15",
        "title":  "形容词与副词",
        "markdown":  "### LessonMeta\n- 目标：区分形容词和副词；掌握基础位置。\n- 预备知识：词类基础。\n- 学习产出：能正确修饰名词和动词。\n\n### WarmupScene\n- 图：运动会画面（fast runner, careful writer）。\n- 对话：\n1. A: She is a fast runner.  \n2. B: She runs fast.  \n3. A: He is a careful student.  \n4. B: He writes carefully.\n\n### RuleCard\n1. 形容词修饰名词：a beautiful flower。  \n2. 副词修饰动词：sing beautifully。  \n3. be动词后常接形容词：She is happy.\n\n### PitfallBox\n- 错：He is happily.  \n  对：He is happy.\n- 错：She sings beautiful.  \n  对：She sings beautifully.\n\n### PracticeA（5）\n1. 选形容词/副词（5句）。  \n2. 改写：`quick -\u003e quickly` 等。  \n3. 填空：`The boy is ___ (careful/carefully).`  \n4. 改错：`He runs quick.`  \n5. 用 be + 形容词写1句。\n\n### PracticeB（3）\n1. 看图写2句“形容词+名词”。  \n2. 写2句“动词+副词”。  \n3. 阅读短文圈出形容词和副词。\n\n### PracticeC（2）\n1. 美化句子挑战：把普通句加上合适形副。  \n2. 综合填空（8空）。\n\n### FunMission\n- 任务：描述力升级赛。给同一张图写“普通版”和“升级版”两段。\n\n### ExitTicket\n1. 哪类词修饰名词？  \n2. `She speaks ___ (good/well).`  \n3. `The soup tastes deliciously.` 如何改？  \n- 自评徽章：`Description Booster`\n\n---"
    },
    {
        "id":  "L16",
        "title":  "比较级与最高级",
        "markdown":  "### LessonMeta\n- 目标：掌握比较级、最高级及不规则变化。\n- 预备知识：形容词基础。\n- 学习产出：能比较两者与三者以上对象。\n\n### WarmupScene\n- 图：三名运动员成绩榜。\n- 对话：\n1. A: Tom is taller than Mike.  \n2. B: But Jack is the tallest.  \n3. A: Math is more difficult than English.  \n4. B: PE is the most exciting for me.\n\n### RuleCard\n1. 两者比较：`比较级 + than`。  \n2. 三者以上：`the + 最高级`。  \n3. 不规则：good-better-best, bad-worse-worst。\n\n### PitfallBox\n- 错：He is more taller than me.  \n  对：He is taller than me.\n- 错：She is best in my class.  \n  对：She is the best in my class.\n\n### PracticeA（5）\n1. 写比较级/最高级：`small, big, happy`  \n2. 选词：better/best, more/most  \n3. 改错：`This book is difficulter.`  \n4. 填空：`My bag is ___ (heavy) than yours.`  \n5. 造句：`the tallest`。\n\n### PracticeB（3）\n1. 用班级数据写3个比较句。  \n2. 看图写1句最高级。  \n3. 完成短文（7空）。\n\n### PracticeC（2）\n1. 运动会数据比拼：根据表格写5句。  \n2. 纠错挑战（6句）。\n\n### FunMission\n- 任务：谁更强？抽角色卡，进行英语比较辩论。\n\n### ExitTicket\n1. 两者比较常用哪个词连接？  \n2. `good` 的最高级是什么？  \n3. `the most tall` 如何改？  \n- 自评徽章：`Comparison Coach`\n\n---"
    },
    {
        "id":  "L17",
        "title":  "介词定位课",
        "markdown":  "### LessonMeta\n- 目标：掌握地点介词与时间介词的基础用法。\n- 预备知识：there be 句型。\n- 学习产出：能准确描述位置和时间。\n\n### WarmupScene\n- 图：教室与日程表。\n- 对话：\n1. A: The cat is under the chair.  \n2. B: The clock is on the wall.  \n3. A: We have English at 8:00.  \n4. B: We have sports on Friday.\n\n### RuleCard\n1. 地点：in/on/under/behind/near/between。  \n2. 时间：`at` 时刻，`on` 具体某天，`in` 月份/年份。  \n3. 介词后接名词或名词短语。\n\n### PitfallBox\n- 错：in Monday  \n  对：on Monday\n- 错：at the morning  \n  对：in the morning\n\n### PracticeA（5）\n1. 图中位置填介词（5空）。  \n2. 时间介词选择（at/on/in）。  \n3. 改错：`The ball is in the desk.`  \n4. 完成句子：`My birthday is ___ July.`  \n5. 写1句 between 句。\n\n### PracticeB（3）\n1. 描述你的房间3句。  \n2. 写一周课程表句子3句。  \n3. 对话填空（地点+时间介词）。\n\n### PracticeC（2）\n1. 地图导航任务：根据指令写路线句。  \n2. 介词纠错短文（5处）。\n\n### FunMission\n- 任务：地图导航员。用英语指导同学从校门走到图书馆。\n\n### ExitTicket\n1. `___ 7:30` 用哪个介词？  \n2. `___ Sunday` 用哪个介词？  \n3. `The bag is on the box.` 画出位置关系。  \n- 自评徽章：`Location Navigator`\n\n---"
    },
    {
        "id":  "L18",
        "title":  "疑问句全家桶",
        "markdown":  "### LessonMeta\n- 目标：掌握一般疑问句和特殊疑问句提问框架。\n- 预备知识：be/do/does/did/will 基础。\n- 学习产出：能提出并回答完整问题。\n\n### WarmupScene\n- 图：校园采访现场。\n- 对话：\n1. A: Do you like science?  \n2. B: Yes, I do.  \n3. A: Where do you have lunch?  \n4. B: We have lunch in the canteen.\n\n### RuleCard\n1. 一般疑问句：be/do/does/did/will 提前。  \n2. 特殊疑问句：`疑问词 + 一般疑问句结构`。  \n3. 回答要完整，不只说单词。\n\n### PitfallBox\n- 错：Where you go?  \n  对：Where do you go?\n- 错：Do she like music?  \n  对：Does she like music?\n\n### PracticeA（5）\n1. 陈述句改一般疑问句（3句）。  \n2. 用 what/where/when/how 填空。  \n3. 配对问答（4组）。  \n4. 改错：`What does he does?`  \n5. 写完整回答：`Do you... ?`\n\n### PracticeB（3）\n1. 设计采访提纲（5个问题）。  \n2. 同伴互访并记录答案。  \n3. 将答案整理成3句报告。\n\n### PracticeC（2）\n1. 疑问句闯关卷（10题）。  \n2. 看图生成“5W1H”问题各1个。\n\n### FunMission\n- 任务：采访小记者。采访3名同学并做英语播报。\n\n### ExitTicket\n1. 特殊疑问句的结构核心是什么？  \n2. `___ do you go to bed?`  \n3. `Where does he goes?` 如何改？  \n- 自评徽章：`Question Master`\n\n---"
    },
    {
        "id":  "L19",
        "title":  "连接词与复合句",
        "markdown":  "### LessonMeta\n- 目标：掌握 and/but/because/so/if 的基础连接功能。\n- 预备知识：简单句写作。\n- 学习产出：能写有逻辑关系的复合句。\n\n### WarmupScene\n- 图：故事四格漫画。\n- 对话：\n1. A: I was tired, so I went to bed early.  \n2. B: I wanted to play, but it rained.  \n3. A: I stayed at home because I had homework.  \n4. B: If it is sunny tomorrow, we will fly kites.\n\n### RuleCard\n1. `and` 并列；`but` 转折。  \n2. `because` 原因；`so` 结果。  \n3. `if` 引导条件（小学阶段先掌握基础条件表达）。\n\n### PitfallBox\n- 错：Because I was late, so I ran fast.  \n  对：I was late, so I ran fast. / Because I was late, I ran fast.\n- 错：If it will rain, we stay home.  \n  对：If it rains, we will stay home.（小学阶段可先记固定搭配）\n\n### PracticeA（5）\n1. 选择连接词填空（5句）。  \n2. 合并短句（3组）。  \n3. 改错：`I like apples but I don\u0027t like bananas and.`  \n4. because/so 互换改写。  \n5. 写1句 if 句。\n\n### PracticeB（3）\n1. 用4个连接词各写1句。  \n2. 补全故事（8空）。  \n3. 判断逻辑是否合理并修改。\n\n### PracticeC（2）\n1. 故事接龙：每人用1个连接词续写。  \n2. 写一段“放学后”微故事（5句，含3种连接词）。\n\n### FunMission\n- 任务：故事接龙工坊。抽取“人物+地点+事件”卡，完成连贯故事。\n\n### ExitTicket\n1. 表示原因常用哪个连接词？  \n2. 表示转折常用哪个连接词？  \n3. 写1句含 `if` 的句子。  \n- 自评徽章：`Logic Linker`\n\n---"
    },
    {
        "id":  "L20",
        "title":  "语法大冒险复盘",
        "markdown":  "### LessonMeta\n- 目标：整合20课语法点，完成综合任务并归因错题。\n- 预备知识：L01-L19。\n- 学习产出：能在语篇中综合使用语法并自我纠错。\n\n### WarmupScene\n- 图：密室通关地图，4道门分别对应词法、句法、时态、逻辑。\n- 对话：\n1. A: We need all grammar keys to open the final door.  \n2. B: Let’s check nouns, tenses and questions first.  \n3. A: I found an error in this sentence.  \n4. B: Great! You are a grammar hero.\n\n### RuleCard\n1. 综合做题顺序：先读语境 -\u003e 找时间词 -\u003e 看主语 -\u003e 定动词形式。  \n2. 检查清单：大小写、标点、主谓一致、时态一致。  \n3. 改错要说明“为什么错”，不是只改答案。\n\n### PitfallBox\n- 错：Yesterday he goes to school and is happy.  \n  对：Yesterday he went to school and was happy.\n- 错：She can sings very well because she practice every day.  \n  对：She can sing very well because she practices every day.\n\n### PracticeA（5）\n1. 全语法选择题（10题）。  \n2. 句型转换（6题）。  \n3. 名词/代词/冠词混合填空（8空）。  \n4. 时态综合填空（8空）。  \n5. 连词逻辑判断（4题）。\n\n### PracticeB（3）\n1. 阅读短文改错（8处）。  \n2. 看图写作：我的周末（6句，含2种时态）。  \n3. 采访问答：3问3答，覆盖疑问句。\n\n### PracticeC（2）\n1. 密室通关总挑战（分关卡积分）。  \n2. 错因归类表：`时态错误/词形错误/结构错误/逻辑错误`。\n\n### FunMission\n- 任务：密室通关总挑战。四人小组分工：读题官、规则官、改错官、汇报官。\n\n### ExitTicket\n1. 今天你最容易错的是哪类？  \n2. 写1句你最满意的英语句子。  \n3. 给自己下阶段目标（1条）。  \n- 自评徽章：`Grammar Hero`"
    }
];
