window.LESSONS = [
    {
        "id":  "L01",
        "title":  "语法地图开营",
        "markdown":  "### LessonMeta\n- 目标：认识词类；理解句子最小结构；知道本课程闯关规则。\n- 预备知识：会读简单单词和句子。\n- 学习产出：能把一句话拆成“谁 + 做什么 + 什么”。\n\n### WarmupScene\n- 图：语法岛地图，5个区域分别是“句子镇、名词港、时态城、比较山、连接桥”。\n- 对话：\n1. A: What is grammar?  \n2. B: Grammar is the rule of good sentences.  \n3. A: Can we learn grammar by games?  \n4. B: Yes, let’s start the adventure!\n\n### RuleCard\n1. 句子至少要有“主语 + 谓语”。  \nExample: I run.\n2. 词有不同工作：名词、动词、形容词、代词等。  \nExample: The small dog runs fast.\n3. 语法不是背定义，而是“在语境里用对句子”。\n\n### TeacherTalk\n- 这一课先不急着背术语，核心是看懂英语句子像积木一样搭起来。\n- 一个完整句子最基本要有“谁”和“做什么”，也就是主语和谓语。\n- 很多孩子只会读词，不会拼句，原因是没有先想清楚“这句话在说谁、说什么动作或状态”。\n- 你可以先用中文想一遍，再翻成英语：谁在做什么，句子就容易写对。\n- 遇到不会写的长句，先找最核心的动作词，再补上主语和必要的信息。\n- 这一课不是要你一次记住所有词类，而是建立一个概念：不同词在句子里有不同工作。\n- 口诀：先找主语，再找谓语，句子先完整，后面再修饰。\r\n\r\n### PitfallBox\n- 错：Run in the park.（无主语）  \n  对：I run in the park.\n- 错：my name is Tom.  \n  对：My name is Tom.\n\n### PracticeA（5）\n1. 圈出主语：`Tom plays football.`  \n2. 圈出动词：`My sister sings well.`  \n3. 补全主语：`___ is my friend.`  \n4. 判断是否是完整句：`In the classroom.`  \n5. 改正大小写：`we are happy.`\n\n### PracticeB（3）\n1. 把词连成句：`play / I / basketball`  \n2. 读句子并标注词类：`The cat is cute.`  \n3. 用“主语+谓语”写1句介绍自己。\n\n### PracticeC（2）\n1. 给图片“公园晨跑”写2句完整句。  \n2. 判断并改错：`Is rainy today.`\n\n### FunMission\n- 任务：语法岛入门卡。把10个词贴到“名词/动词/形容词”三栏。\n\n### ExitTicket\n1. 句子最少需要哪两个部分？  \n2. 在 `Lucy reads books.` 中，哪个是谓语？  \n3. `my dog is black.` 怎么改？  \n- 自评徽章：`Grammar Explorer`\n\n---"
    },
    {
        "id":  "L02",
        "title":  "句子零件工厂",
        "markdown":  "### LessonMeta\n- 目标：掌握主语/谓语/宾语；规范大小写和标点。\n- 预备知识：L01。\n- 学习产出：能拼装并改写基本陈述句。\n\n### WarmupScene\n- 图：机器人句子工厂，零件箱标有 S / V / O。\n- 对话：\n1. A: What does S-V-O mean?  \n2. B: Subject, Verb, Object.  \n3. A: Can every sentence use S-V-O?  \n4. B: Many sentences can.\n\n### RuleCard\n1. 常见句型：S + V + O。  \nExample: We love English.\n2. 句首字母大写，句末用 `.` `?` `!`。  \n3. 人称代词 `I` 永远大写。\n\n### TeacherTalk\n- 这一课要解决的是“句子怎么站稳”的问题。主语、谓语、宾语是句子的骨架。\n- 陈述句里，最常见的结构就是“谁 + 做什么 + 什么对象”，这就是 S + V + O。\n- 句首大写、句末标点看起来简单，但它们决定了句子是不是像样的书面英语。\n- `I` 永远大写，不是因为它很特别，而是英语书写习惯要求第一人称单数永远写成大写。\n- 如果句子里少了主语，读起来会像“碎片”，不能算完整句。\n- 如果句子里只写了主语和地点，没有动作，也通常不够完整。\n- 写完句子后，先做一个小检查：有没有大写？有没有句号/问号/感叹号？句子有没有说完整？\r\n\r\n### PitfallBox\n- 错：i like apples  \n  对：I like apples.\n- 错：She is a doctor?（陈述句误用问号）  \n  对：She is a doctor.\n\n### PracticeA（5）\n1. 标注S/V/O：`They watch TV.`  \n2. 改正：`he play football.`  \n3. 选标点：`What is your name__`  \n4. 补全宾语：`I read ___.`  \n5. 改为完整句：`My brother in Grade 6.`\n\n### PracticeB（3）\n1. 用 `S+V+O` 写2句校园生活。  \n2. 找错并改：`we are classmates!`  \n3. 将 `She likes music.` 改成否定句。\n\n### PracticeC（2）\n1. 看图（操场）写3句，至少1句用 `!`。  \n2. 句子重排：`in / studies / Lucy / the library`\n\n### FunMission\n- 任务：句子拼装赛。小组抽3张词卡，60秒拼出正确句。\n\n### ExitTicket\n1. `I` 什么时候要大写？  \n2. `Tom eats lunch.` 的宾语是什么？  \n3. `she is happy` 如何规范书写？  \n- 自评徽章：`Sentence Builder`\n\n---"
    },
    {
        "id":  "L03",
        "title":  "名词特工队",
        "markdown":  "### LessonMeta\n- 目标：区分可数/不可数名词；掌握常见复数变化。\n- 预备知识：L01-L02。\n- 学习产出：能根据数量正确选择名词形式。\n\n### WarmupScene\n- 图：超市货架，一边是 apples/books，另一边是 milk/rice。\n- 对话：\n1. A: How many apples do you want?  \n2. B: Three apples, please.  \n3. A: How much milk do you want?  \n4. B: A little milk.\n\n### RuleCard\n1. 可数名词可数数量，有单复数。  \nExample: one book / two books\n2. 不可数名词一般无复数。  \nExample: water, milk, rice\n3. 复数常见变化：`-s/-es`，特殊：`child-children`、`man-men`。\n\n### TeacherTalk\n- 名词就是“人、物、地点、概念”的名字，孩子先要学会判断它是“一个”还是“很多个”。\n- 可数名词像苹果、书、学生，可以数个数，所以有单复数变化。\n- 不可数名词像牛奶、水、米饭，通常不能直接说 `two milk`，因为英语里它们不是这样计数的。\n- 复数形式不是随便加 `s`，很多词还要加 `es`，少数词会不规则变化。\n- 你可以把名词想成“货架上的商品”：能单独拿出来数的，多数是可数；像液体、材料、抽象概念，很多是不可数。\n- 如果题目里出现 `how many`，先想可数复数；如果出现 `how much`，先想不可数名词。\n- 这课最重要的不是背词表，而是学会判断“这个词能不能数”。\r\n\r\n### PitfallBox\n- 错：two bread  \n  对：two pieces of bread\n- 错：three childs  \n  对：three children\n\n### PracticeA（5）\n1. 写复数：`bus, box, baby`  \n2. 判断可数/不可数：`juice, pen, rice`  \n3. 选词：`How many/how much` water?  \n4. 改错：`two milks`  \n5. 填空：`There are five ___ (tomato).`\n\n### PracticeB（3）\n1. 设计购物单：5个可数+3个不可数。  \n2. 用 `How many` 和 `How much` 各写1问1答。  \n3. 改写：`I have a child.` -\u003e 复数句。\n\n### PracticeC（2）\n1. 看图（冰箱）写4句数量表达。  \n2. 完成分类表：把12个名词分到可数/不可数。\n\n### FunMission\n- 任务：超市采购挑战。预算50元，写英语采购清单并口头汇报。\n\n### ExitTicket\n1. `information` 是可数还是不可数？  \n2. `knife` 的复数如何写？  \n3. `How much apples...?` 为什么错？  \n- 自评徽章：`Noun Agent`\n\n---"
    },
    {
        "id":  "L04",
        "title":  "冠词与数量词",
        "markdown":  "### LessonMeta\n- 目标：掌握 a/an/the 与 some/any/many/much 的用法。\n- 预备知识：L03。\n- 学习产出：能在句子中正确选冠词和数量词。\n\n### WarmupScene\n- 图：早餐桌上有 egg, apple, bread, milk。\n- 对话：\n1. A: I want an egg and an apple.  \n2. B: Do you want any milk?  \n3. A: Yes, I need some milk.  \n4. B: Great, here is the milk.\n\n### RuleCard\n1. `a/an` 表示“一个”，`an` 用于元音音素开头词。  \n2. `the` 表示特指（双方都知道的那个）。  \n3. `some` 常用于肯定句，`any` 常用于否定/疑问句；`many+可数复数`，`much+不可数`。\n\n### TeacherTalk\n- 冠词和数量词是小学英语最容易乱的地方，因为它们很小，但作用很大。\n- `a/an` 不是看字母，是看读音：元音音素开头用 `an`，辅音音素开头用 `a`。\n- `the` 是“我知道你也知道”的那个，表示特指，不是随便乱用。\n- `some` 和 `any` 经常一起考，先记住：肯定句常用 `some`，疑问句和否定句常用 `any`。\n- `many` 搭配可数复数，`much` 搭配不可数名词，这个规则在写数量表达时特别常见。\n- 你如果看到一大堆词，不要先乱选，先判断名词能不能数、是不是特指、句子是不是问句或否定句。\n- 这节课的核心能力，是让你“用小词把数量说准确”。\r\n\r\n### PitfallBox\n- 错：a apple  \n  对：an apple\n- 错：much books  \n  对：many books\n\n### PracticeA（5）\n1. 选冠词：`__ orange, __ university, __ sun`  \n2. some/any 填空：`Do you have ___ pencils?`  \n3. many/much 填空：`How ___ water?`  \n4. 改错：`I need any help.`  \n5. 选词：`This is ___ book on the desk.`\n\n### PracticeB（3）\n1. 写3句：各用 a/an/the。  \n2. 看图写2个 some/any 问答句。  \n3. 改写：`I have books.` -\u003e 用 many。\n\n### PracticeC（2）\n1. 早餐点单对话补全（8空）。  \n2. 阅读短文，圈出所有冠词并说明作用。\n\n### FunMission\n- 任务：食物篮配对赛。把词卡放进正确篮子：`a/an/the/some/any`。\n\n### ExitTicket\n1. 为什么是 `an hour`？  \n2. `the` 和 `a` 最大区别是什么？  \n3. `many milk` 如何改？  \n- 自评徽章：`Article Master`\n\n---"
    },
    {
        "id":  "L05",
        "title":  "代词换装秀",
        "markdown":  "### LessonMeta\n- 目标：掌握主格、宾格、形容词性物主代词、名词性物主代词。\n- 预备知识：L02。\n- 学习产出：能避免重复名词并正确替换。\n\n### WarmupScene\n- 图：三位同学交换文具。\n- 对话：\n1. A: This is my pen.  \n2. B: Is it yours?  \n3. C: We like her bag.  \n4. A: She gives it to us.\n\n### RuleCard\n1. 主格作主语：I, you, he, she, it, we, they。  \n2. 宾格作宾语：me, you, him, her, it, us, them。  \n3. 物主代词：`my/your...` + 名词；`mine/yours...` 可单独使用。\n\n### TeacherTalk\n- 代词是为了避免重复，让句子更自然、更顺口。\n- 主格代词负责当主语，宾格代词负责当宾语，这个分工一定要记清。\n- 形容词性物主代词后面一定要跟名词，比如 `my book`；名词性物主代词后面不能再跟名词，比如 `mine`。\n- 很多孩子会把 `my` 和 `mine` 混用，本质上是没分清“后面有没有名词”。\n- 这节课不只是替换词，更是训练你在一句话里避免重复，让表达更像母语者。\n- 当你发现一个名字出现了两次、三次，先想能不能换成代词，句子会更自然。\n- 口诀：主语用主格，宾语用宾格，后面跟名词用 my/your/his，单独使用用 mine/yours/his。\r\n\r\n### PitfallBox\n- 错：Me am a student.  \n  对：I am a student.\n- 错：This is my.  \n  对：This is mine.\n\n### PracticeA（5）\n1. 选主格/宾格：`___ (He/Him) likes me.`  \n2. 填空：`This is ___ (my/mine) book.`  \n3. 改写：`The bike is Tom\u0027s.` -\u003e `The bike is ___ .`  \n4. 改错：`Her is my friend.`  \n5. 选词：`Please help ___ (I/me).`\n\n### PracticeB（3）\n1. 用 `I/me/my/mine` 各写1句。  \n2. 两人对话：借文具，至少用4个代词。  \n3. 把重复名词改为代词：`Lucy likes Lucy\u0027s dog.`\n\n### PracticeC（2）\n1. 阅读短文，替换10处重复名词为代词。  \n2. 纠错题（6句）中找出代词错误并改正。\n\n### FunMission\n- 任务：角色替换卡。抽“人物卡+动作卡”，把名词句瞬间改成代词句。\n\n### ExitTicket\n1. `She helps ___ (we/us).` 选哪个？  \n2. `This ruler is ___ (my/mine).` 选哪个？  \n3. `Them are in the room.` 如何改？  \n- 自评徽章：`Pronoun Stylist`\n\n---"
    },
    {
        "id":  "L06",
        "title":  "Be动词指挥官",
        "markdown":  "### LessonMeta\n- 目标：掌握 am/is/are 的选择及肯否疑变换。\n- 预备知识：代词。\n- 学习产出：能熟练完成 be 句三种句型转换。\n\n### WarmupScene\n- 图：班级点名场景。\n- 对话：\n1. A: I am here.  \n2. B: She is not late.  \n3. C: Are they in the classroom?  \n4. D: Yes, they are.\n\n### RuleCard\n1. `I am`，`he/she/it is`，`you/we/they are`。  \n2. 否定句：be 后加 not。  \n3. 一般疑问句：be 提前，回答用 `Yes/No + 主语 + be`。\n\n### TeacherTalk\n- `am/is/are` 是英语最基础的“系动词”，它们不是动作动词，而是把主语和状态、身份、地点连接起来。\n- 选 `am/is/are` 的第一步，不是看中文意思，而是先看主语是谁。\n- `I am` 是固定搭配，`he/she/it is`，`you/we/they are`，这套要形成条件反射。\n- 否定句只是在 be 后面加 `not`，一般疑问句就是把 be 提到句首。\n- 很多孩子会把 `be` 和 `do/does` 混在一起，记住：be 句型和实义动词句型是两套系统。\n- 这课的目标不是机械变形，而是让你一看到主语就能立刻选对 be 动词。\n- 口诀：I 用 am，单数 he/she/it 用 is，复数 you/we/they 用 are。\r\n\r\n### PitfallBox\n- 错：He are a boy.  \n  对：He is a boy.\n- 错：Are she happy?  \n  对：Is she happy?\n\n### PracticeA（5）\n1. 填空：`I ___ happy.`  \n2. 变否定：`They are ready.`  \n3. 变疑问：`She is at home.`  \n4. 回答：`Are you a student?`  \n5. 改错：`We is friends.`\n\n### PracticeB（3）\n1. 看图写3个be句（肯/否/疑各1）。  \n2. 对话补全（am/is/are）。  \n3. 造句：用 `there` + be（预热L07）。\n\n### PracticeC（2）\n1. 把短文中8个be动词改正确。  \n2. 抢答：老师读主语，你快速说 be 形式。\n\n### FunMission\n- 任务：错句急救站。3分钟抢救10个错误 be 句。\n\n### ExitTicket\n1. `I` 搭配哪个 be？  \n2. `He is tall.` 的疑问句是什么？  \n3. `They am not here.` 如何改？  \n- 自评徽章：`Be Commander`\n\n---"
    },
    {
        "id":  "L07",
        "title":  "There be空间站",
        "markdown":  "### LessonMeta\n- 目标：掌握 there is/there are，会描述位置。\n- 预备知识：be动词、名词单复数。\n- 学习产出：能准确表达“某地有某物”。\n\n### WarmupScene\n- 图：卧室俯视图（bed, desk, books, lamp）。\n- 对话：\n1. A: There is a bed in my room.  \n2. B: There are two books on the desk.  \n3. A: Is there a lamp near the bed?  \n4. B: Yes, there is.\n\n### RuleCard\n1. `There is + 单数/不可数`；`There are + 复数`。  \n2. 地点介词常见：in/on/under/near。  \n3. 疑问句：`Is/Are there ...?`\n\n### TeacherTalk\n- `there be` 表示“某地有某物”，重点不是“谁有”，而是“哪里存在什么”。\n- 先判断后面的名词是单数还是复数，再决定用 `there is` 还是 `there are`。\n- `there be` 和 `have/has` 不一样：`there be` 说“存在”，`have/has` 说“拥有”。\n- 地点介词像一个定位器，告诉别人东西在什么位置。\n- 描述房间时，先说大范围，再说小范围，会更清楚：房间里有什么、桌子上有什么、床下面有什么。\n- 这节课真正要培养的是“空间表达能力”，不是只会背 `there is/are`。\n- 口诀：单数不可数用 is，复数用 are；描述位置先观察，再下笔。\r\n\r\n### PitfallBox\n- 错：There are a cat on the chair.  \n  对：There is a cat on the chair.\n- 错：There is two pens.  \n  对：There are two pens.\n\n### PracticeA（5）\n1. is/are 填空（5句）。  \n2. 看图填地点介词。  \n3. 改错：`Are there a book?`  \n4. 变否定：`There is some juice.`  \n5. 变疑问：`There are three boys.`\n\n### PracticeB（3）\n1. 描述你的书包（至少3句 there be）。  \n2. 两图找不同，用 there be 写2句。  \n3. 与 L06 对比：`There is` vs `It is`。\n\n### PracticeC（2）\n1. 完成“我的梦想教室”描述短文（8空）。  \n2. 听描述，画出物品位置（可口头）。\n\n### FunMission\n- 任务：房间寻宝图。根据英文线索找5个物品并写句子。\n\n### ExitTicket\n1. `There ___ some water.` 填什么？  \n2. `There are a dog...` 错在哪？  \n3. 用 there be 造1句关于教室的话。  \n- 自评徽章：`Space Reporter`\n\n---"
    },
    {
        "id":  "L08",
        "title":  "一般现在时",
        "markdown":  "### LessonMeta\n- 目标：真正理解一般现在时的3个最常见用途，学会在陈述、提问、改错中正确使用。\n- 预备知识：会说简单的现在时句子；知道动词原形和 `be` 动词。\n- 学习产出：能写“我的一天”和“朋友的一天”，并能把错误的现在时句子改对。\n\n### WarmupScene\n- 图：时间轴（get up, go to school, do homework）。\n- 对话：\n1. A: I get up at 6:30 every day.  \n2. B: My brother goes to school at 7:10.  \n3. A: Does he like school?  \n4. B: Yes, he does.\n\n### RuleCard\n1. 一般现在时最常见的 3 种意思：\n   - 习惯动作：I get up at 6:30 every day.\n   - 经常发生的事：She often reads after dinner.\n   - 客观事实：The sun rises in the east.\n2. 主语是三单（he/she/it 或单数名词）时，动词要变形：\n   - watch -\u003e watches\n   - study -\u003e studies\n   - play -\u003e plays\n3. 否定和疑问句要借助 `do/does`：\n   - I/you/we/they 用 `do`\n   - he/she/it 用 `does`\n   - `does` 后面的动词要回到原形\n4. 频率副词通常放在实义动词前面，放在 `be` 后面：\n   - I often play football.\n   - She is always happy.\n\n### TeacherTalk\n- 一般现在时不是“现在这一秒正在发生”，而是“经常发生、习惯发生、客观事实”。\n- 先分清：一般现在时的 3 个常见用途是习惯、经常性的动作和事实。\n- 三单加 `-s/-es` 是英语里专门给第三人称单数主语做的标记，主语是 he/she/it 或单数名词时必须注意。\n- `do/does` 只是帮忙做否定和提问，后面的动词要回原形，这一点非常容易错。\n- 频率副词像一个“小标签”，`always/often/sometimes/never` 告诉别人动作发生的频率。\n- 如果你不确定时态，先问自己：这句话是在说“习惯”、还是“正在发生”、还是“过去发生”？\n- 口诀：经常习惯事实说现在，三单动词加 s，问和否定找 do/does。\r\n\n### PitfallBox\n- 错：He go to school by bus.  \n  对：He goes to school by bus.\n- 错：Does she likes music?  \n  对：Does she like music?\n- 错：She often goes always to school.  \n  对：She always goes to school.\n- 错：He don\u0027t like milk.  \n  对：He doesn\u0027t like milk.\n\n### PracticeA（5）\n1. 写出三单形式：`watch, study, play, go, do`  \n2. 改否定：`Tom likes milk.`  \n3. 改疑问：`They play tennis.`  \n4. 频率副词填空：always/often/sometimes/never  \n5. 改错：`My father don\u0027t cook.`\n\n### PracticeB（3）\n1. 写“我的一天”5句，至少2句三单。  \n2. 两人互问作息，完成问卷。  \n3. 阅读短文找出所有一般现在时动词，并圈出 `do/does`。\n\n### PracticeC（2）\n1. 句型转换综合（6小题）。  \n2. 写一段“我的好朋友”并标注三单动词。\n\n### FunMission\n- 任务：日常时间轴挑战。把打乱的活动按时间排序，并说出每句为什么要用一般现在时。\n\n### ExitTicket\n1. 一般现在时最常表示哪 3 类意思？  \n2. `He doesn\u0027t ___ (like/likes) PE.`  \n3. 写1句带 `often` 的一般现在时。  \n- 自评徽章：`Daily Routine Pro`\n\n---"
    },
    {
        "id":  "L09",
        "title":  "现在进行时",
        "markdown":  "### LessonMeta\n- 目标：掌握 be + V-ing；识别现在进行时提示词。\n- 预备知识：be动词、动词原形。\n- 学习产出：能描述“此刻正在发生”的动作。\n\n### WarmupScene\n- 图：直播画面，多个学生在做不同动作。\n- 对话：\n1. A: Look! Tom is running.  \n2. B: Lucy is reading now.  \n3. A: Are they playing basketball?  \n4. B: No, they aren’t.\n\n### RuleCard\n1. 结构：`am/is/are + V-ing`。  \n2. 常见提示词：now, look, listen, at the moment。  \n3. 一般疑问句：be 提前。\n\n### TeacherTalk\n- 现在进行时描述的是“眼前正在发生”的动作，所以它一定和“现在这一刻”有关。\n- 结构很固定：`be + 动词ing`，先选对 be，再把动词变成 ing 形式。\n- 现在进行时特别喜欢和提示词一起出现，比如 `now`、`look`、`listen`、`at the moment`。\n- 很多孩子会把一般现在时和现在进行时混在一起，最简单的分法就是：是否正在发生。\n- 进行时里，be 动词必须在，不能只写 `She reading`。\n- 读图说话时，如果画面里人物正在做动作，优先考虑进行时。\n- 口诀：看见正在做，先想 be + ing。\r\n\r\n### PitfallBox\n- 错：She reading now.  \n  对：She is reading now.\n- 错：They are play football.  \n  对：They are playing football.\n\n### PracticeA（5）\n1. 动词改 ing：`swim, make, write`  \n2. 选时态：now / every day。  \n3. 改否定：`I am drawing.`  \n4. 改疑问：`He is singing.`  \n5. 改错：`Are you do homework?`\n\n### PracticeB（3）\n1. 看图写4句进行时。  \n2. 与一般现在时对比填空（6空）。  \n3. 两人对话：电话里问“你在做什么”。\n\n### PracticeC（2）\n1. “教室直播”配音：给6张图各写1句。  \n2. 阅读短文，圈出非进行时并改正。\n\n### FunMission\n- 任务：直播间解说员。30秒连续用进行时口播画面。\n\n### ExitTicket\n1. 现在进行时的核心结构是什么？  \n2. `Look! It ___ (rain).`  \n3. `He is play.` 如何改？  \n- 自评徽章：`Live Commentator`\n\n---"
    },
    {
        "id":  "L10",
        "title":  "一般过去时①（规则动词）",
        "markdown":  "### LessonMeta\n- 目标：掌握规则过去式；理解过去时间状语。\n- 预备知识：一般现在时。\n- 学习产出：能写“昨天发生了什么”。\n\n### WarmupScene\n- 图：昨天的校园活动照片墙。\n- 对话：\n1. A: What did you do yesterday?  \n2. B: I played football and watched TV.  \n3. A: Did you finish your homework?  \n4. B: Yes, I did.\n\n### RuleCard\n1. 一般过去时表示过去发生的动作。  \n2. 规则动词常加 `-ed`（play-played, watch-watched）。  \n3. 否定/疑问常用 `did/didn\u0027t`，后接动词原形。\n\n### TeacherTalk\n- 一般过去时是“已经发生并结束”的动作，所以常常会和 `yesterday`、`last week`、`ago` 这些时间词一起出现。\n- 规则动词过去式通常加 `-ed`，但拼写要注意变化：`stop -\u003e stopped`、`study -\u003e studied`。\n- `did` 出现后，后面的动词必须回原形，这是过去时最常见的语法点之一。\n- 很多孩子会把过去式和现在时混在一起，看到过去时间词时，先提醒自己“动作已经结束”。\n- 这节课的重点不是死背，而是建立时间感：过去发生的事情，句子形式也要跟着变。\n- 口诀：过去时间词来了，动词形式要变；有 did 就回原形。\r\n\r\n### PitfallBox\n- 错：I didn\u0027t went to school.  \n  对：I didn\u0027t go to school.\n- 错：Did he played basketball?  \n  对：Did he play basketball?\n\n### PracticeA（5）\n1. 写过去式：`clean, dance, stop`  \n2. 选时间词：yesterday/now/tomorrow  \n3. 改否定：`She visited her grandma.`  \n4. 改疑问：`They watched a film.`  \n5. 改错：`We goed home early.`\n\n### PracticeB（3）\n1. 完成“我的昨天”4句。  \n2. 问答配对：`Did you...?`  \n3. 读短文找出过去时动词。\n\n### PracticeC（2）\n1. 写“上周末小日记”（5句）。  \n2. 句型混合改写（肯/否/疑）。\n\n### FunMission\n- 任务：昨日新闻播报。每组写3条“Yesterday News”并播报。\n\n### ExitTicket\n1. `did` 后面动词用什么形式？  \n2. `I ___ (visit) my uncle yesterday.`  \n3. `Did she went...?` 如何改？  \n- 自评徽章：`Past Reporter`\n\n---"
    },
    {
        "id":  "L11",
        "title":  "一般过去时②（不规则动词）",
        "markdown":  "### LessonMeta\n- 目标：掌握常见不规则过去式；强化 did 句型转换。\n- 预备知识：L10。\n- 学习产出：能在问答中正确使用过去式。\n\n### WarmupScene\n- 图：周末活动卡片（go, eat, see, buy）。\n- 对话：\n1. A: Where did you go last Sunday?  \n2. B: I went to the zoo.  \n3. A: What did you eat there?  \n4. B: I ate a hot dog.\n\n### RuleCard\n1. 常见不规则：go-went, eat-ate, see-saw, buy-bought, have-had。  \n2. 过去时问句：`Did + 主语 + 动词原形 ...?`  \n3. 回答：`Yes, ... did.` / `No, ... didn\u0027t.`\n\n### TeacherTalk\n- 这一课继续练过去时，但重点从“规则变化”转到“不规则变化”。\n- 不规则动词没有统一加 `-ed` 的规律，所以只能靠常见词组块记忆。\n- `go-went`、`eat-ate`、`see-saw`、`buy-bought`、`have-had` 是最常考的一批。\n- 做问句和否定句时，只要有 `did`，后面的动词就不能再用过去式。\n- 很多错题不是不会单词，而是把 `did` 和过去式同时用了，造成“双重过去”。\n- 这节课要训练的是“听到过去时间，就能自动调出过去式”。\n- 口诀：不规则靠积累，问句否定用 did，后面动词回原形。\r\n\r\n### PitfallBox\n- 错：I goed to the park.  \n  对：I went to the park.\n- 错：What did you ate?  \n  对：What did you eat?\n\n### PracticeA（5）\n1. 配对不规则动词原形与过去式。  \n2. 填空：`She ___ (have) a cold yesterday.`  \n3. 改问句：`He saw a bird.`  \n4. 回答：`Did they buy books?`  \n5. 改错：`We didn\u0027t saw him.`\n\n### PracticeB（3）\n1. 采访同桌：昨天做了什么（3问3答）。  \n2. 用 `went/ate/saw` 各写1句。  \n3. 短文改错（4处）。\n\n### PracticeC（2）\n1. 记忆翻牌：20个不规则动词快配。  \n2. 写“上次春游”6句，至少3个不规则动词。\n\n### FunMission\n- 任务：记忆翻牌PK。限时记住并说出过去式。\n\n### ExitTicket\n1. `go` 的过去式是什么？  \n2. `Did he ___ (saw/see) it?`  \n3. `I didn\u0027t went.` 如何改？  \n- 自评徽章：`Time Traveler`\n\n---"
    },
    {
        "id":  "L12",
        "title":  "一般将来时",
        "markdown":  "### LessonMeta\n- 目标：掌握 be going to 与 will 的基础用法。\n- 预备知识：一般现在/过去时。\n- 学习产出：能表达计划与简单预测。\n\n### WarmupScene\n- 图：周末计划板（picnic, movie, homework）。\n- 对话：\n1. A: What are you going to do this weekend?  \n2. B: I am going to visit my grandparents.  \n3. A: Will it rain tomorrow?  \n4. B: I think it will.\n\n### RuleCard\n1. `be going to` 常表示已有计划。  \n2. `will` 常表示临时决定或预测。  \n3. 将来时间词：tomorrow, next week, soon。\n\n### TeacherTalk\n- 一般将来时说的是“还没发生，但计划要发生、或很可能会发生”。\n- `be going to` 更像“已经有安排”，`will` 更像“临时决定”或“预测”。\n- 这两种结构都属于将来时，孩子先会用，再慢慢学细分区别。\n- 句子里看到 `tomorrow`、`next week`、`soon`、`this weekend`，要先想到将来时。\n- `will` 后面一定接动词原形，不能再加三单变化。\n- 这节课不是只会说计划，而是要学会把“未来的事”用正确句型表达出来。\n- 口诀：计划常用 going to，临时决定常用 will。\r\n\r\n### PitfallBox\n- 错：I going to play football.  \n  对：I am going to play football.\n- 错：Will you to come?  \n  对：Will you come?\n\n### PracticeA（5）\n1. 填 be：`She ___ going to read.`  \n2. will/be going to 选择（5句）。  \n3. 改否定：`They will win.`  \n4. 改疑问：`You are going to swim.`  \n5. 改错：`He will goes home.`\n\n### PracticeB（3）\n1. 写3个周末计划句。  \n2. 预测明天天气2句。  \n3. 对话补全（8空）。\n\n### PracticeC（2）\n1. 设计“假期计划海报”英文文案（5句）。  \n2. 综合选择题（时态混合）。\n\n### FunMission\n- 任务：周末计划师。和同伴互相提问并做计划表。\n\n### ExitTicket\n1. `will` 后接动词什么形式？  \n2. `I ___ going to clean my room.`  \n3. `Will she plays...?` 如何改？  \n- 自评徽章：`Future Planner`\n\n---"
    },
    {
        "id":  "L13",
        "title":  "时态对比总练",
        "markdown":  "### LessonMeta\n- 目标：辨析一般现在、现在进行、一般过去、一般将来。\n- 预备知识：L08-L12。\n- 学习产出：能按时间线选择正确时态。\n\n### WarmupScene\n- 图：时光隧道（past-now-future）。\n- 对话：\n1. A: I play basketball every day.  \n2. B: I am playing now.  \n3. A: I played yesterday.  \n4. B: I will play tomorrow.\n\n### RuleCard\n1. 先看时间词，再选时态。  \n2. 进行时看“正在发生”；一般现在看“习惯事实”。  \n3. 过去与将来要注意动词形式变化。\n\n### TeacherTalk\n- 这一课的目的，是让你学会“看时间选时态”，而不是靠猜。\n- 先抓时间词，再判断动作是习惯、正在发生、过去完成，还是未来安排。\n- 一般现在时、现在进行时、一般过去时、一般将来时是小学阶段最重要的 4 个时态。\n- 做题时先读时间，再看主语，再定动词形式，这是最稳的顺序。\n- 很多题错不是因为不会单个时态，而是把几个时态混在一起了。\n- 如果你能把时间线在脑子里排出来，时态题就会容易很多。\n- 口诀：先看时间，再看动作，再定时态。\r\n\r\n### PitfallBox\n- 错：Yesterday I play football.  \n  对：Yesterday I played football.\n- 错：Now he plays the piano.  \n  对：Now he is playing the piano.\n\n### PracticeA（5）\n1. 时间词配时态（5组）。  \n2. 动词正确形式填空（8空）。  \n3. 找出句子时态并标记。  \n4. 改错（4句）。  \n5. 快速分类：10句放入4种时态。\n\n### PracticeB（3）\n1. 写“昨天-今天-明天”各2句。  \n2. 阅读短文，完成时态选择。  \n3. 口头问答：老师给时间词，你造句。\n\n### PracticeC（2）\n1. 时光隧道挑战卷（10题综合）。  \n2. 写小段落《My Busy Weekend》（含3种时态）。\n\n### FunMission\n- 任务：时光隧道选择题闯关，答对解锁下一关。\n\n### ExitTicket\n1. `now` 常对应哪种时态？  \n2. `last week` 常对应哪种时态？  \n3. 写1句将来时。  \n- 自评徽章：`Tense Detective`\n\n---"
    },
    {
        "id":  "L14",
        "title":  "情态动词入门",
        "markdown":  "### LessonMeta\n- 目标：掌握 can/can\u0027t, must/mustn\u0027t, should 的基本语义。\n- 预备知识：基础句子结构。\n- 学习产出：能表达能力、规则与建议。\n\n### WarmupScene\n- 图：校园规则海报。\n- 对话：\n1. A: Can you swim?  \n2. B: Yes, I can.  \n3. A: Must we run in the hall?  \n4. B: No, we mustn\u0027t.\n\n### RuleCard\n1. `can` 表能力；`can\u0027t` 表不能。  \n2. `must` 表必须；`mustn\u0027t` 表禁止。  \n3. `should` 表建议，语气较温和。\n\n### TeacherTalk\n- 情态动词不是普通动作词，它们是“说能力、规则、建议”的帮手。\n- `can` 表能力，`must` 表必须，`should` 表建议，这三类意思完全不同。\n- 情态动词后面都接动词原形，不要再加 `-s`、`-ing` 或 `to`。\n- 这节课特别适合联系学校生活：能不能做、必须不必须做、应该怎么做。\n- `mustn\u0027t` 是“禁止”，语气比 `don\u0027t` 更像规则和命令。\n- 孩子做情态动词题，先看场景：是能力，还是规则，还是建议。\n- 口诀：能用 can，必须用 must，建议用 should，后面动词回原形。\r\n\r\n### PitfallBox\n- 错：He can swims.  \n  对：He can swim.\n- 错：You mustn\u0027t to eat here.  \n  对：You mustn\u0027t eat here.\n\n### PracticeA（5）\n1. can/can\u0027t 填空（5句）。  \n2. must/mustn\u0027t 选词（校园规则）。  \n3. should 造句（健康建议）。  \n4. 改错：`She can sings.`  \n5. 回答：`Can you ride a bike?`\n\n### PracticeB（3）\n1. 写3条班级规则（must/mustn\u0027t）。  \n2. 给朋友3条建议（should）。  \n3. 对话补全（6空）。\n\n### PracticeC（2）\n1. 情景写作：`At the library`（4句）。  \n2. 抢答：听情景选情态动词。\n\n### FunMission\n- 任务：校园规则法官。判断行为是否合规并给出句子。\n\n### ExitTicket\n1. 情态动词后面动词用什么形式？  \n2. `You ___ be quiet in class.`  \n3. `He can to swim.` 如何改？  \n- 自评徽章：`Rule Keeper`\n\n---"
    },
    {
        "id":  "L15",
        "title":  "形容词与副词",
        "markdown":  "### LessonMeta\n- 目标：区分形容词和副词；掌握基础位置。\n- 预备知识：词类基础。\n- 学习产出：能正确修饰名词和动词。\n\n### WarmupScene\n- 图：运动会画面（fast runner, careful writer）。\n- 对话：\n1. A: She is a fast runner.  \n2. B: She runs fast.  \n3. A: He is a careful student.  \n4. B: He writes carefully.\n\n### RuleCard\n1. 形容词修饰名词：a beautiful flower。  \n2. 副词修饰动词：sing beautifully。  \n3. be动词后常接形容词：She is happy.\n\n### TeacherTalk\n- 形容词和副词都是“修饰词”，但它们修饰的对象不一样。\n- 形容词主要修饰名词，副词主要修饰动词。\n- `be` 动词后面常接形容词，不要把副词直接放在 `is/are/am` 后面。\n- 很多孩子会把 `good` 和 `well`、`quick` 和 `quickly` 混淆，本质上是没分清修饰对象。\n- 这节课要学的是：先看词是修饰谁，再决定用形容词还是副词。\n- 通过加修饰词，句子会更有画面感，也更像真实表达。\n- 口诀：修饰名词用形容词，修饰动作用副词。\r\n\r\n### PitfallBox\n- 错：He is happily.  \n  对：He is happy.\n- 错：She sings beautiful.  \n  对：She sings beautifully.\n\n### PracticeA（5）\n1. 选形容词/副词（5句）。  \n2. 改写：`quick -\u003e quickly` 等。  \n3. 填空：`The boy is ___ (careful/carefully).`  \n4. 改错：`He runs quick.`  \n5. 用 be + 形容词写1句。\n\n### PracticeB（3）\n1. 看图写2句“形容词+名词”。  \n2. 写2句“动词+副词”。  \n3. 阅读短文圈出形容词和副词。\n\n### PracticeC（2）\n1. 美化句子挑战：把普通句加上合适形副。  \n2. 综合填空（8空）。\n\n### FunMission\n- 任务：描述力升级赛。给同一张图写“普通版”和“升级版”两段。\n\n### ExitTicket\n1. 哪类词修饰名词？  \n2. `She speaks ___ (good/well).`  \n3. `The soup tastes deliciously.` 如何改？  \n- 自评徽章：`Description Booster`\n\n---"
    },
    {
        "id":  "L16",
        "title":  "比较级与最高级",
        "markdown":  "### LessonMeta\n- 目标：掌握比较级、最高级及不规则变化。\n- 预备知识：形容词基础。\n- 学习产出：能比较两者与三者以上对象。\n\n### WarmupScene\n- 图：三名运动员成绩榜。\n- 对话：\n1. A: Tom is taller than Mike.  \n2. B: But Jack is the tallest.  \n3. A: Math is more difficult than English.  \n4. B: PE is the most exciting for me.\n\n### RuleCard\n1. 两者比较：`比较级 + than`。  \n2. 三者以上：`the + 最高级`。  \n3. 不规则：good-better-best, bad-worse-worst。\n\n### TeacherTalk\n- 比较级是“两者比较”，最高级是“三者或以上比较”。\n- `than` 常和比较级一起出现，`the` 常和最高级一起出现。\n- 不是所有词都简单加 `-er/-est`，有些要用 `more/most`，还有一些是不规则变化。\n- 这节课最重要的是比较的逻辑，不是死记某一个词形。\n- 先想比较对象是两个还是三个以上，再决定用哪种形式。\n- 如果两个词都很长，通常用 `more/most` 更自然。\n- 口诀：两者比较用比较级，三者以上用最高级。\r\n\r\n### PitfallBox\n- 错：He is more taller than me.  \n  对：He is taller than me.\n- 错：She is best in my class.  \n  对：She is the best in my class.\n\n### PracticeA（5）\n1. 写比较级/最高级：`small, big, happy`  \n2. 选词：better/best, more/most  \n3. 改错：`This book is difficulter.`  \n4. 填空：`My bag is ___ (heavy) than yours.`  \n5. 造句：`the tallest`。\n\n### PracticeB（3）\n1. 用班级数据写3个比较句。  \n2. 看图写1句最高级。  \n3. 完成短文（7空）。\n\n### PracticeC（2）\n1. 运动会数据比拼：根据表格写5句。  \n2. 纠错挑战（6句）。\n\n### FunMission\n- 任务：谁更强？抽角色卡，进行英语比较辩论。\n\n### ExitTicket\n1. 两者比较常用哪个词连接？  \n2. `good` 的最高级是什么？  \n3. `the most tall` 如何改？  \n- 自评徽章：`Comparison Coach`\n\n---"
    },
    {
        "id":  "L17",
        "title":  "介词定位课",
        "markdown":  "### LessonMeta\n- 目标：掌握地点介词与时间介词的基础用法。\n- 预备知识：there be 句型。\n- 学习产出：能准确描述位置和时间。\n\n### WarmupScene\n- 图：教室与日程表。\n- 对话：\n1. A: The cat is under the chair.  \n2. B: The clock is on the wall.  \n3. A: We have English at 8:00.  \n4. B: We have sports on Friday.\n\n### RuleCard\n1. 地点：in/on/under/behind/near/between。  \n2. 时间：`at` 时刻，`on` 具体某天，`in` 月份/年份。  \n3. 介词后接名词或名词短语。\n\n### TeacherTalk\n- 介词是英语里的“定位词”，能把人、物、时间、位置说清楚。\n- 地点介词管空间，时间介词管时间，两个系统不要混。\n- `in/on/under/behind/near/between` 这些词看起来简单，但特别常考。\n- 时间介词里，`at` 管具体时刻，`on` 管具体某天，`in` 管月份、年份和较大的时间段。\n- 如果你会画图，就更容易做对介词题：先在脑子里把东西摆出来，再选介词。\n- 这节课的目标是“让别人一听就知道在哪儿、什么时候”。\n- 口诀：时刻用 at，日期用 on，月份年份用 in。\r\n\r\n### PitfallBox\n- 错：in Monday  \n  对：on Monday\n- 错：at the morning  \n  对：in the morning\n\n### PracticeA（5）\n1. 图中位置填介词（5空）。  \n2. 时间介词选择（at/on/in）。  \n3. 改错：`The ball is in the desk.`  \n4. 完成句子：`My birthday is ___ July.`  \n5. 写1句 between 句。\n\n### PracticeB（3）\n1. 描述你的房间3句。  \n2. 写一周课程表句子3句。  \n3. 对话填空（地点+时间介词）。\n\n### PracticeC（2）\n1. 地图导航任务：根据指令写路线句。  \n2. 介词纠错短文（5处）。\n\n### FunMission\n- 任务：地图导航员。用英语指导同学从校门走到图书馆。\n\n### ExitTicket\n1. `___ 7:30` 用哪个介词？  \n2. `___ Sunday` 用哪个介词？  \n3. `The bag is on the box.` 画出位置关系。  \n- 自评徽章：`Location Navigator`\n\n---"
    },
    {
        "id":  "L18",
        "title":  "疑问句全家桶",
        "markdown":  "### LessonMeta\n- 目标：掌握一般疑问句和特殊疑问句提问框架。\n- 预备知识：be/do/does/did/will 基础。\n- 学习产出：能提出并回答完整问题。\n\n### WarmupScene\n- 图：校园采访现场。\n- 对话：\n1. A: Do you like science?  \n2. B: Yes, I do.  \n3. A: Where do you have lunch?  \n4. B: We have lunch in the canteen.\n\n### RuleCard\n1. 一般疑问句：be/do/does/did/will 提前。  \n2. 特殊疑问句：`疑问词 + 一般疑问句结构`。  \n3. 回答要完整，不只说单词。\n\n### TeacherTalk\n- 疑问句是英语里很重要的沟通工具，因为你要先会问，才会聊。\n- 一般疑问句的核心是“把帮助词提到前面”，特殊疑问句则是“疑问词 + 一般疑问句结构”。\n- `What/Where/When/How` 是小学阶段最常用的四类疑问词。\n- 回答问题时，要注意答完整句，不要只说一个单词。\n- 这节课既考“怎么问”，也考“怎么答”，所以要双向练习。\n- 先学会问自己，再学会问别人，英语对话就会变得自然。\n- 口诀：先看是一般问还是特殊问，再选对结构。\r\n\r\n### PitfallBox\n- 错：Where you go?  \n  对：Where do you go?\n- 错：Do she like music?  \n  对：Does she like music?\n\n### PracticeA（5）\n1. 陈述句改一般疑问句（3句）。  \n2. 用 what/where/when/how 填空。  \n3. 配对问答（4组）。  \n4. 改错：`What does he does?`  \n5. 写完整回答：`Do you... ?`\n\n### PracticeB（3）\n1. 设计采访提纲（5个问题）。  \n2. 同伴互访并记录答案。  \n3. 将答案整理成3句报告。\n\n### PracticeC（2）\n1. 疑问句闯关卷（10题）。  \n2. 看图生成“5W1H”问题各1个。\n\n### FunMission\n- 任务：采访小记者。采访3名同学并做英语播报。\n\n### ExitTicket\n1. 特殊疑问句的结构核心是什么？  \n2. `___ do you go to bed?`  \n3. `Where does he goes?` 如何改？  \n- 自评徽章：`Question Master`\n\n---"
    },
    {
        "id":  "L19",
        "title":  "连接词与复合句",
        "markdown":  "### LessonMeta\n- 目标：掌握 and/but/because/so/if 的基础连接功能。\n- 预备知识：简单句写作。\n- 学习产出：能写有逻辑关系的复合句。\n\n### WarmupScene\n- 图：故事四格漫画。\n- 对话：\n1. A: I was tired, so I went to bed early.  \n2. B: I wanted to play, but it rained.  \n3. A: I stayed at home because I had homework.  \n4. B: If it is sunny tomorrow, we will fly kites.\n\n### RuleCard\n1. `and` 并列；`but` 转折。  \n2. `because` 原因；`so` 结果。  \n3. `if` 引导条件（小学阶段先掌握基础条件表达）。\n\n### TeacherTalk\n- 连接词的作用是把短句连起来，让表达有逻辑、有关系。\n- `and` 是并列，`but` 是转折，`because` 表原因，`so` 表结果，`if` 表条件。\n- 很多孩子会把 `because` 和 `so` 同时用在同一句里，导致逻辑重复。\n- 写故事时，不只是把句子连上，还要让前后关系合理。\n- 这节课其实是在训练“英语思维逻辑”，不是简单背单词。\n- 如果你能说清“为什么、结果是什么、条件是什么”，句子就会很成熟。\n- 口诀：并列 and，转折 but，原因 because，结果 so，条件 if。\r\n\r\n### PitfallBox\n- 错：Because I was late, so I ran fast.  \n  对：I was late, so I ran fast. / Because I was late, I ran fast.\n- 错：If it will rain, we stay home.  \n  对：If it rains, we will stay home.（小学阶段可先记固定搭配）\n\n### PracticeA（5）\n1. 选择连接词填空（5句）。  \n2. 合并短句（3组）。  \n3. 改错：`I like apples but I don\u0027t like bananas and.`  \n4. because/so 互换改写。  \n5. 写1句 if 句。\n\n### PracticeB（3）\n1. 用4个连接词各写1句。  \n2. 补全故事（8空）。  \n3. 判断逻辑是否合理并修改。\n\n### PracticeC（2）\n1. 故事接龙：每人用1个连接词续写。  \n2. 写一段“放学后”微故事（5句，含3种连接词）。\n\n### FunMission\n- 任务：故事接龙工坊。抽取“人物+地点+事件”卡，完成连贯故事。\n\n### ExitTicket\n1. 表示原因常用哪个连接词？  \n2. 表示转折常用哪个连接词？  \n3. 写1句含 `if` 的句子。  \n- 自评徽章：`Logic Linker`\n\n---"
    },
    {
        "id":  "L20",
        "title":  "语法大冒险复盘",
        "markdown":  "### LessonMeta\n- 目标：整合20课语法点，完成综合任务并归因错题。\n- 预备知识：L01-L19。\n- 学习产出：能在语篇中综合使用语法并自我纠错。\n\n### WarmupScene\n- 图：密室通关地图，4道门分别对应词法、句法、时态、逻辑。\n- 对话：\n1. A: We need all grammar keys to open the final door.  \n2. B: Let’s check nouns, tenses and questions first.  \n3. A: I found an error in this sentence.  \n4. B: Great! You are a grammar hero.\n\n### RuleCard\n1. 综合做题顺序：先读语境 -\u003e 找时间词 -\u003e 看主语 -\u003e 定动词形式。  \n2. 检查清单：大小写、标点、主谓一致、时态一致。  \n3. 改错要说明“为什么错”，不是只改答案。\n\n### TeacherTalk\n- 总复盘不是再学新知识，而是把前面 19 课的语法放在一起使用。\n- 做综合题时，先看时间词、主语、句型，再决定时态和动词形式。\n- 看到错误不要只改答案，要能说出“错在哪儿、为什么错”。\n- 这节课最重要的是自我检查能力：大小写、标点、主谓一致、时态一致、词形变化。\n- 当你会把名词、代词、时态、比较级、疑问句和连接词串起来，说明你已经开始真正会用英语。\n- 综合题的难点不在某一个知识点，而在于多个知识点一起出现时能不能保持清醒。\n- 口诀：先看语境，再看时间，再看主语，最后检查形式。\r\n\r\n### PitfallBox\n- 错：Yesterday he goes to school and is happy.  \n  对：Yesterday he went to school and was happy.\n- 错：She can sings very well because she practice every day.  \n  对：She can sing very well because she practices every day.\n\n### PracticeA（5）\n1. 全语法选择题（10题）。  \n2. 句型转换（6题）。  \n3. 名词/代词/冠词混合填空（8空）。  \n4. 时态综合填空（8空）。  \n5. 连词逻辑判断（4题）。\n\n### PracticeB（3）\n1. 阅读短文改错（8处）。  \n2. 看图写作：我的周末（6句，含2种时态）。  \n3. 采访问答：3问3答，覆盖疑问句。\n\n### PracticeC（2）\n1. 密室通关总挑战（分关卡积分）。  \n2. 错因归类表：`时态错误/词形错误/结构错误/逻辑错误`。\n\n### FunMission\n- 任务：密室通关总挑战。四人小组分工：读题官、规则官、改错官、汇报官。\n\n### ExitTicket\n1. 今天你最容易错的是哪类？  \n2. 写1句你最满意的英语句子。  \n3. 给自己下阶段目标（1条）。  \n- 自评徽章：`Grammar Hero`"
    }
];
