window.LESSONS = [
    {
        "id":  "L01",
        "title":  "语法地图开营",
        "markdown":  "### LessonMeta\n- 目标：认识词类；理解句子最小结构；知道本课程闯关规则。\n- 预备知识：会读简单单词和句子。\n- 学习产出：能把一句话拆成“谁 + 做什么 + 什么”。\n\n### WarmupScene\n- 图：语法岛地图，5个区域分别是“句子镇、名词港、时态城、比较山、连接桥”。\n- 对话：\n1. A: What is grammar?  \n2. B: Grammar is the rule of good sentences.  \n3. A: Can we learn grammar by games?  \n4. B: Yes, let’s start the adventure!\n\n### RuleCard\n1. 句子至少要有“主语 + 谓语”。  \nExample: I run.\n2. 词有不同工作：名词、动词、形容词、代词等。  \nExample: The small dog runs fast.\n3. 语法不是背定义，而是“在语境里用对句子”。\n\n### TeacherTalk\n- 本课重点在于建立句子结构的基本认知，而非记忆术语。\n- 英语句子的核心结构为”主语 + 谓语”：主语回答”谁”，谓语回答”做什么”或”是什么”。\n- 初学阶段可先用中文组织”谁 + 做什么”，再转换为英语表达。\n- 遇到较长句子时，优先锁定核心动词，再补充主语及其他成分。\n- 词类（名词、动词、形容词等）各有功能，本课以建立概念为主。\n- 口诀：先找主语，再找谓语，句子先完整，后面再修饰。\r\n\r\n### PitfallBox\n- 错：Run in the park.（无主语）  \n  对：I run in the park.\n- 错：my name is Tom.  \n  对：My name is Tom.\n\n### PracticeA（5）\n1. 圈出主语：`Tom plays football.`  \n2. 圈出动词：`My sister sings well.`  \n3. 补全主语：`___ is my friend.`  \n4. 判断是否是完整句：`In the classroom.`  \n5. 改正大小写：`we are happy.`\n\n### PracticeB（3）\n1. 把词连成句：`play / I / basketball`  \n2. 读句子并标注词类：`The cat is cute.`  \n3. 用“主语+谓语”写1句介绍自己。\n\n### PracticeC（2）\n1. 给图片“公园晨跑”写2句完整句。  \n2. 判断并改错：`Is rainy today.`\n\n### FunMission\n- 任务：语法岛入门卡。把10个词贴到“名词/动词/形容词”三栏。\n\n### ExitTicket\n1. 句子最少需要哪两个部分？  \n2. 在 `Lucy reads books.` 中，哪个是谓语？  \n3. `my dog is black.` 怎么改？  \n- 自评徽章：`Grammar Explorer`\n\n---"
    },
    {
        "id":  "L02",
        "title":  "句子零件工厂",
        "markdown":  "### LessonMeta\n- 目标：掌握主语/谓语/宾语；规范大小写和标点。\n- 预备知识：L01。\n- 学习产出：能拼装并改写基本陈述句。\n\n### WarmupScene\n- 图：机器人句子工厂，零件箱标有 S / V / O。\n- 对话：\n1. A: What does S-V-O mean?  \n2. B: Subject, Verb, Object.  \n3. A: Can every sentence use S-V-O?  \n4. B: Many sentences can.\n\n### RuleCard\n1. 常见句型：S + V + O。  \nExample: We love English.\n2. 句首字母大写，句末用 `.` `?` `!`。  \n3. 人称代词 `I` 永远大写。\n\n### TeacherTalk\n- 本课聚焦句子的基本骨架：主语（S）+ 谓语（V）+ 宾语（O）。\n- 陈述句最常见的结构为 S + V + O，即”谁 + 做什么 + 什么对象”。\n- 句首字母必须大写，句末必须使用正确的标点符号（. ? !）。\n- 第一人称代词 `I` 在任何位置均需大写，这是英语书写规范。\n- 缺少主语或缺少谓语的句子均不完整，不符合书面英语要求。\n- 完成书写后应逐项检查：大写、标点、主谓是否齐全。\n- 口诀：S + V + O 是骨架，大写标点不能少。\r\n\r\n### PitfallBox\n- 错：i like apples  \n  对：I like apples.\n- 错：She is a doctor?（陈述句误用问号）  \n  对：She is a doctor.\n\n### PracticeA（5）\n1. 标注S/V/O：`They watch TV.`  \n2. 改正：`he play football.`  \n3. 选标点：`What is your name__`  \n4. 补全宾语：`I read ___.`  \n5. 改为完整句：`My brother in Grade 6.`\n\n### PracticeB（3）\n1. 用 `S+V+O` 写2句校园生活。  \n2. 找错并改：`we are classmates!`  \n3. 将 `She likes music.` 改成否定句。\n\n### PracticeC（2）\n1. 看图（操场）写3句，至少1句用 `!`。  \n2. 句子重排：`in / studies / Lucy / the library`\n\n### FunMission\n- 任务：句子拼装赛。小组抽3张词卡，60秒拼出正确句。\n\n### ExitTicket\n1. `I` 什么时候要大写？  \n2. `Tom eats lunch.` 的宾语是什么？  \n3. `she is happy` 如何规范书写？  \n- 自评徽章：`Sentence Builder`\n\n---"
    },
    {
        "id":  "L03",
        "title":  "名词特工队",
        "markdown":  "### LessonMeta\n- 目标：区分可数/不可数名词；掌握常见复数变化。\n- 预备知识：L01-L02。\n- 学习产出：能根据数量正确选择名词形式。\n\n### WarmupScene\n- 图：超市货架，一边是 apples/books，另一边是 milk/rice。\n- 对话：\n1. A: How many apples do you want?  \n2. B: Three apples, please.  \n3. A: How much milk do you want?  \n4. B: A little milk.\n\n### RuleCard\n1. 可数名词可数数量，有单复数。  \nExample: one book / two books\n2. 不可数名词一般无复数。  \nExample: water, milk, rice\n3. 复数常见变化：`-s/-es`，特殊：`child-children`、`man-men`。\n\n### TeacherTalk\n- 名词用于指称人、事物、地点或抽象概念，需首先判断其可数性。\n- 可数名词有单复数变化，如 book → books；不可数名词通常无复数形式。\n- 常见不可数名词包括：water, milk, rice, bread, information 等。\n- 复数变化规则：一般加 -s；以 s/x/ch/sh 结尾加 -es；部分词不规则变化（child → children, man → men）。\n- 数量表达中，how many 修饰可数复数，how much 修饰不可数名词。\n- 判断可数性的方法：能否用具体数字直接修饰。能则可数，不能则不可数。\n- 口诀：可数名词有单复，不可数名词不加 s；how many 数得清，how much 不可数。\r\n\r\n### PitfallBox\n- 错：two bread  \n  对：two pieces of bread\n- 错：three childs  \n  对：three children\n\n### PracticeA（5）\n1. 写复数：`bus, box, baby`  \n2. 判断可数/不可数：`juice, pen, rice`  \n3. 选词：`How many/how much` water?  \n4. 改错：`two milks`  \n5. 填空：`There are five ___ (tomato).`\n\n### PracticeB（3）\n1. 设计购物单：5个可数+3个不可数。  \n2. 用 `How many` 和 `How much` 各写1问1答。  \n3. 改写：`I have a child.` -\u003e 复数句。\n\n### PracticeC（2）\n1. 看图（冰箱）写4句数量表达。  \n2. 完成分类表：把12个名词分到可数/不可数。\n\n### FunMission\n- 任务：超市采购挑战。预算50元，写英语采购清单并口头汇报。\n\n### ExitTicket\n1. `information` 是可数还是不可数？  \n2. `knife` 的复数如何写？  \n3. `How much apples...?` 为什么错？  \n- 自评徽章：`Noun Agent`\n\n---"
    },
    {
        "id":  "L04",
        "title":  "冠词与数量词",
        "markdown":  "### LessonMeta\n- 目标：掌握 a/an/the 与 some/any/many/much 的用法。\n- 预备知识：L03。\n- 学习产出：能在句子中正确选冠词和数量词。\n\n### WarmupScene\n- 图：早餐桌上有 egg, apple, bread, milk。\n- 对话：\n1. A: I want an egg and an apple.  \n2. B: Do you want any milk?  \n3. A: Yes, I need some milk.  \n4. B: Great, here is the milk.\n\n### RuleCard\n1. `a/an` 表示“一个”，`an` 用于元音音素开头词。  \n2. `the` 表示特指（双方都知道的那个）。  \n3. `some` 常用于肯定句，`any` 常用于否定/疑问句；`many+可数复数`，`much+不可数`。\n\n### TeacherTalk\n- 冠词（a/an/the）与数量词（some/any/many/much）是英语中的功能词，使用频率极高。\n- `a` 用于辅音音素开头的词前，`an` 用于元音音素开头的词前。判断依据是读音而非字母。\n- `the` 表示特指，即说话双方均明确所指对象时使用。\n- `some` 常用于肯定句，`any` 常用于否定句和疑问句。\n- `many` 修饰可数名词复数，`much` 修饰不可数名词。\n- 选择步骤：先判断名词可数性 → 再判断是否特指 → 最后根据句式选择。\n- 口诀：元音前用 an，特指用 the，肯定 some 否定 any。\r\n\r\n### PitfallBox\n- 错：a apple  \n  对：an apple\n- 错：much books  \n  对：many books\n\n### PracticeA（5）\n1. 选冠词：`__ orange, __ university, __ sun`  \n2. some/any 填空：`Do you have ___ pencils?`  \n3. many/much 填空：`How ___ water?`  \n4. 改错：`I need any help.`  \n5. 选词：`This is ___ book on the desk.`\n\n### PracticeB（3）\n1. 写3句：各用 a/an/the。  \n2. 看图写2个 some/any 问答句。  \n3. 改写：`I have books.` -\u003e 用 many。\n\n### PracticeC（2）\n1. 早餐点单对话补全（8空）。  \n2. 阅读短文，圈出所有冠词并说明作用。\n\n### FunMission\n- 任务：食物篮配对赛。把词卡放进正确篮子：`a/an/the/some/any`。\n\n### ExitTicket\n1. 为什么是 `an hour`？  \n2. `the` 和 `a` 最大区别是什么？  \n3. `many milk` 如何改？  \n- 自评徽章：`Article Master`\n\n---"
    },
    {
        "id":  "L05",
        "title":  "代词换装秀",
        "markdown":  "### LessonMeta\n- 目标：掌握主格、宾格、形容词性物主代词、名词性物主代词。\n- 预备知识：L02。\n- 学习产出：能避免重复名词并正确替换。\n\n### WarmupScene\n- 图：三位同学交换文具。\n- 对话：\n1. A: This is my pen.  \n2. B: Is it yours?  \n3. C: We like her bag.  \n4. A: She gives it to us.\n\n### RuleCard\n1. 主格作主语：I, you, he, she, it, we, they。  \n2. 宾格作宾语：me, you, him, her, it, us, them。  \n3. 物主代词：`my/your...` + 名词；`mine/yours...` 可单独使用。\n\n### TeacherTalk\n- 代词用于替代名词，避免重复，使表达更加简洁自然。\n- 主格代词（I/you/he/she/it/we/they）在句中充当主语。\n- 宾格代词（me/you/him/her/it/us/them）在句中充当宾语。\n- 形容词性物主代词（my/your/his/her/its/our/their）后必须接名词。\n- 名词性物主代词（mine/yours/his/hers/its/ours/theirs）可独立使用，后不接名词。\n- 使用代词的关键在于分清”后面是否还有名词”，由此决定使用哪种物主代词。\n- 口诀：主语用主格，宾语用宾格；后有名词用 my/your/his，独立使用用 mine/yours/his。\r\n\r\n### PitfallBox\n- 错：Me am a student.  \n  对：I am a student.\n- 错：This is my.  \n  对：This is mine.\n\n### PracticeA（5）\n1. 选主格/宾格：`___ (He/Him) likes me.`  \n2. 填空：`This is ___ (my/mine) book.`  \n3. 改写：`The bike is Tom\u0027s.` -\u003e `The bike is ___ .`  \n4. 改错：`Her is my friend.`  \n5. 选词：`Please help ___ (I/me).`\n\n### PracticeB（3）\n1. 用 `I/me/my/mine` 各写1句。  \n2. 两人对话：借文具，至少用4个代词。  \n3. 把重复名词改为代词：`Lucy likes Lucy\u0027s dog.`\n\n### PracticeC（2）\n1. 阅读短文，替换10处重复名词为代词。  \n2. 纠错题（6句）中找出代词错误并改正。\n\n### FunMission\n- 任务：角色替换卡。抽“人物卡+动作卡”，把名词句瞬间改成代词句。\n\n### ExitTicket\n1. `She helps ___ (we/us).` 选哪个？  \n2. `This ruler is ___ (my/mine).` 选哪个？  \n3. `Them are in the room.` 如何改？  \n- 自评徽章：`Pronoun Stylist`\n\n---"
    },
    {
        "id":  "L06",
        "title":  "Be动词指挥官",
        "markdown":  "### LessonMeta\n- 目标：掌握 am/is/are 的选择及肯否疑变换。\n- 预备知识：代词。\n- 学习产出：能熟练完成 be 句三种句型转换。\n\n### WarmupScene\n- 图：班级点名场景。\n- 对话：\n1. A: I am here.  \n2. B: She is not late.  \n3. C: Are they in the classroom?  \n4. D: Yes, they are.\n\n### RuleCard\n1. `I am`，`he/she/it is`，`you/we/they are`。  \n2. 否定句：be 后加 not。  \n3. 一般疑问句：be 提前，回答用 `Yes/No + 主语 + be`。\n\n### TeacherTalk\n- `am/is/are` 是英语中最基础的系动词，用于连接主语与状态、身份或地点。\n- 选择依据为主语人称和数：I 搭配 am，he/she/it 搭配 is，you/we/they 搭配 are。\n- 否定句在 be 后加 `not`；一般疑问句将 be 提至句首，回答格式为 Yes/No + 主语 + be。\n- be 动词句型与实义动词句型（do/does）是两套独立系统，不可混淆。\n- 本课目标是形成条件反射：看到主语即可准确选择对应的 be 动词。\n- 口诀：I 用 am，he/she/it 用 is，you/we/they 用 are。\r\n\r\n### PitfallBox\n- 错：He are a boy.  \n  对：He is a boy.\n- 错：Are she happy?  \n  对：Is she happy?\n\n### PracticeA（5）\n1. 填空：`I ___ happy.`  \n2. 变否定：`They are ready.`  \n3. 变疑问：`She is at home.`  \n4. 回答：`Are you a student?`  \n5. 改错：`We is friends.`\n\n### PracticeB（3）\n1. 看图写3个be句（肯/否/疑各1）。  \n2. 对话补全（am/is/are）。  \n3. 造句：用 `there` + be（预热L07）。\n\n### PracticeC（2）\n1. 把短文中8个be动词改正确。  \n2. 抢答：老师读主语，你快速说 be 形式。\n\n### FunMission\n- 任务：错句急救站。3分钟抢救10个错误 be 句。\n\n### ExitTicket\n1. `I` 搭配哪个 be？  \n2. `He is tall.` 的疑问句是什么？  \n3. `They am not here.` 如何改？  \n- 自评徽章：`Be Commander`\n\n---"
    },
    {
        "id":  "L07",
        "title":  "There be空间站",
        "markdown":  "### LessonMeta\n- 目标：掌握 there is/there are，会描述位置。\n- 预备知识：be动词、名词单复数。\n- 学习产出：能准确表达“某地有某物”。\n\n### WarmupScene\n- 图：卧室俯视图（bed, desk, books, lamp）。\n- 对话：\n1. A: There is a bed in my room.  \n2. B: There are two books on the desk.  \n3. A: Is there a lamp near the bed?  \n4. B: Yes, there is.\n\n### RuleCard\n1. `There is + 单数/不可数`；`There are + 复数`。  \n2. 地点介词常见：in/on/under/near。  \n3. 疑问句：`Is/Are there ...?`\n\n### TeacherTalk\n- `there be` 句型表示”某地存在某物”，强调存在性而非拥有性。\n- be 动词的选择取决于其后名词的数：单数或不可数名词用 is，复数名词用 are。\n- `there be` 与 `have/has` 的区别：`there be` 表示”某处存在”，`have/has` 表示”某人拥有”。\n- 地点介词（in/on/under/near/between）用于精确描述位置关系。\n- 描述空间时，建议从大范围到小范围依次表述，使表达层次清晰。\n- 口诀：单数不可数用 is，复数用 are；存在用 there be，拥有用 have/has。\r\n\r\n### PitfallBox\n- 错：There are a cat on the chair.  \n  对：There is a cat on the chair.\n- 错：There is two pens.  \n  对：There are two pens.\n\n### PracticeA（5）\n1. is/are 填空（5句）。  \n2. 看图填地点介词。  \n3. 改错：`Are there a book?`  \n4. 变否定：`There is some juice.`  \n5. 变疑问：`There are three boys.`\n\n### PracticeB（3）\n1. 描述你的书包（至少3句 there be）。  \n2. 两图找不同，用 there be 写2句。  \n3. 与 L06 对比：`There is` vs `It is`。\n\n### PracticeC（2）\n1. 完成“我的梦想教室”描述短文（8空）。  \n2. 听描述，画出物品位置（可口头）。\n\n### FunMission\n- 任务：房间寻宝图。根据英文线索找5个物品并写句子。\n\n### ExitTicket\n1. `There ___ some water.` 填什么？  \n2. `There are a dog...` 错在哪？  \n3. 用 there be 造1句关于教室的话。  \n- 自评徽章：`Space Reporter`\n\n---"
    },
    {
        "id":  "L08",
        "title":  "一般现在时",
        "markdown":  "### LessonMeta\n- 目标：真正理解一般现在时的3个最常见用途，学会在陈述、提问、改错中正确使用。\n- 预备知识：会说简单的现在时句子；知道动词原形和 `be` 动词。\n- 学习产出：能写“我的一天”和“朋友的一天”，并能把错误的现在时句子改对。\n\n### WarmupScene\n- 图：时间轴（get up, go to school, do homework）。\n- 对话：\n1. A: I get up at 6:30 every day.  \n2. B: My brother goes to school at 7:10.  \n3. A: Does he like school?  \n4. B: Yes, he does.\n\n### RuleCard\n1. 一般现在时最常见的 3 种意思：\n   - 习惯动作：I get up at 6:30 every day.\n   - 经常发生的事：She often reads after dinner.\n   - 客观事实：The sun rises in the east.\n2. 主语是三单（he/she/it 或单数名词）时，动词要变形：\n   - watch -\u003e watches\n   - study -\u003e studies\n   - play -\u003e plays\n3. 否定和疑问句要借助 `do/does`：\n   - I/you/we/they 用 `do`\n   - he/she/it 用 `does`\n   - `does` 后面的动词要回到原形\n4. 频率副词通常放在实义动词前面，放在 `be` 后面：\n   - I often play football.\n   - She is always happy.\n\n### TeacherTalk\n- 一般现在时用于表达习惯性动作、经常性事件或客观事实，而非此刻正在发生。\n- 三类典型用法：习惯动作、经常性事件、客观事实。\n- 第三人称单数主语（he/she/it 或单数名词）时，动词需加 -s/-es。\n- 否定句和疑问句借助 do/does 构成，does 后动词必须恢复原形。\n- 频率副词（always/often/sometimes/never）通常置于实义动词之前、be 动词之后。\n- 判断时态的方法：先明确动作属于习惯、正在发生还是过去发生。\n- 口诀：经常习惯事实说现在，三单动词加 s，问和否定找 do/does。\n### PitfallBox\n- 错：He go to school by bus.  \n  对：He goes to school by bus.\n- 错：Does she likes music?  \n  对：Does she like music?\n- 错：She often goes always to school.  \n  对：She always goes to school.\n- 错：He don\u0027t like milk.  \n  对：He doesn\u0027t like milk.\n\n### PracticeA（5）\n1. 写出三单形式：`watch, study, play, go, do`  \n2. 改否定：`Tom likes milk.`  \n3. 改疑问：`They play tennis.`  \n4. 频率副词填空：always/often/sometimes/never  \n5. 改错：`My father don\u0027t cook.`\n\n### PracticeB（3）\n1. 写“我的一天”5句，至少2句三单。  \n2. 两人互问作息，完成问卷。  \n3. 阅读短文找出所有一般现在时动词，并圈出 `do/does`。\n\n### PracticeC（2）\n1. 句型转换综合（6小题）。  \n2. 写一段“我的好朋友”并标注三单动词。\n\n### FunMission\n- 任务：日常时间轴挑战。把打乱的活动按时间排序，并说出每句为什么要用一般现在时。\n\n### ExitTicket\n1. 一般现在时最常表示哪 3 类意思？  \n2. `He doesn\u0027t ___ (like/likes) PE.`  \n3. 写1句带 `often` 的一般现在时。  \n- 自评徽章：`Daily Routine Pro`\n\n---"
    },
    {
        "id":  "L09",
        "title":  "现在进行时",
        "markdown":  "### LessonMeta\n- 目标：掌握 be + V-ing；识别现在进行时提示词。\n- 预备知识：be动词、动词原形。\n- 学习产出：能描述“此刻正在发生”的动作。\n\n### WarmupScene\n- 图：直播画面，多个学生在做不同动作。\n- 对话：\n1. A: Look! Tom is running.  \n2. B: Lucy is reading now.  \n3. A: Are they playing basketball?  \n4. B: No, they aren’t.\n\n### RuleCard\n1. 结构：`am/is/are + V-ing`。  \n2. 常见提示词：now, look, listen, at the moment。  \n3. 一般疑问句：be 提前。\n\n### TeacherTalk\n- 现在进行时描述说话时刻正在发生的动作，与此刻直接相关。\n- 固定结构：be（am/is/are）+ 动词-ing 形式，be 动词不可省略。\n- 常见提示词：now, look, listen, at the moment，出现时优先考虑进行时。\n- 与一般现在时的区分要点：一般现在时表习惯或事实，现在进行时表正在发生。\n- be 动词缺失是常见错误，如 She reading now 应改为 She is reading now。\n- 口诀：看见正在做，先想 be + ing。\n### PitfallBox\n- 错：She reading now.  \n  对：She is reading now.\n- 错：They are play football.  \n  对：They are playing football.\n\n### PracticeA（5）\n1. 动词改 ing：`swim, make, write`  \n2. 选时态：now / every day。  \n3. 改否定：`I am drawing.`  \n4. 改疑问：`He is singing.`  \n5. 改错：`Are you do homework?`\n\n### PracticeB（3）\n1. 看图写4句进行时。  \n2. 与一般现在时对比填空（6空）。  \n3. 两人对话：电话里问“你在做什么”。\n\n### PracticeC（2）\n1. “教室直播”配音：给6张图各写1句。  \n2. 阅读短文，圈出非进行时并改正。\n\n### FunMission\n- 任务：直播间解说员。30秒连续用进行时口播画面。\n\n### ExitTicket\n1. 现在进行时的核心结构是什么？  \n2. `Look! It ___ (rain).`  \n3. `He is play.` 如何改？  \n- 自评徽章：`Live Commentator`\n\n---"
    },
    {
        "id":  "L10",
        "title":  "一般过去时①（规则动词）",
        "markdown":  "### LessonMeta\n- 目标：掌握规则过去式；理解过去时间状语。\n- 预备知识：一般现在时。\n- 学习产出：能写“昨天发生了什么”。\n\n### WarmupScene\n- 图：昨天的校园活动照片墙。\n- 对话：\n1. A: What did you do yesterday?  \n2. B: I played football and watched TV.  \n3. A: Did you finish your homework?  \n4. B: Yes, I did.\n\n### RuleCard\n1. 一般过去时表示过去发生的动作。  \n2. 规则动词常加 `-ed`（play-played, watch-watched）。  \n3. 否定/疑问常用 `did/didn\u0027t`，后接动词原形。\n\n### TeacherTalk\n- 一般过去时表示过去已发生并结束的动作，常与 yesterday, last week, ago 等时间状语共现。\n- 规则动词过去式通常加 -ed，但需注意拼写变化。\n- 否定句和疑问句使用 did/didn't，其后动词必须恢复原形。\n- 过去式与现在时不可混用，出现过去时间词时应自动切换为过去时态。\n- 核心要求：建立时间意识，使句子形式与时间信息保持一致。\n- 口诀：过去时间词来了，动词形式要变；有 did 就回原形。\n### PitfallBox\n- 错：I didn\u0027t went to school.  \n  对：I didn\u0027t go to school.\n- 错：Did he played basketball?  \n  对：Did he play basketball?\n\n### PracticeA（5）\n1. 写过去式：`clean, dance, stop`  \n2. 选时间词：yesterday/now/tomorrow  \n3. 改否定：`She visited her grandma.`  \n4. 改疑问：`They watched a film.`  \n5. 改错：`We goed home early.`\n\n### PracticeB（3）\n1. 完成“我的昨天”4句。  \n2. 问答配对：`Did you...?`  \n3. 读短文找出过去时动词。\n\n### PracticeC（2）\n1. 写“上周末小日记”（5句）。  \n2. 句型混合改写（肯/否/疑）。\n\n### FunMission\n- 任务：昨日新闻播报。每组写3条“Yesterday News”并播报。\n\n### ExitTicket\n1. `did` 后面动词用什么形式？  \n2. `I ___ (visit) my uncle yesterday.`  \n3. `Did she went...?` 如何改？  \n- 自评徽章：`Past Reporter`\n\n---"
    },
    {
        "id":  "L11",
        "title":  "一般过去时②（不规则动词）",
        "markdown":  "### LessonMeta\n- 目标：掌握常见不规则过去式；强化 did 句型转换。\n- 预备知识：L10。\n- 学习产出：能在问答中正确使用过去式。\n\n### WarmupScene\n- 图：周末活动卡片（go, eat, see, buy）。\n- 对话：\n1. A: Where did you go last Sunday?  \n2. B: I went to the zoo.  \n3. A: What did you eat there?  \n4. B: I ate a hot dog.\n\n### RuleCard\n1. 常见不规则：go-went, eat-ate, see-saw, buy-bought, have-had。  \n2. 过去时问句：`Did + 主语 + 动词原形 ...?`  \n3. 回答：`Yes, ... did.` / `No, ... didn\u0027t.`\n\n### TeacherTalk\n- 本课聚焦不规则动词的过去式变化，需通过常见词组强化记忆。\n- 高频不规则动词：go-went, eat-ate, see-saw, buy-bought, have-had。\n- 否定句和疑问句中使用 did 后，动词必须恢复原形，避免双重过去错误。\n- 常见错误类型：did 与过去式并用，如 Did he played 应改为 Did he play。\n- 训练目标：听到过去时间词时，能够自动调用正确的过去式形式。\n- 口诀：不规则靠积累，问句否定用 did，后面动词回原形。\n### PitfallBox\n- 错：I goed to the park.  \n  对：I went to the park.\n- 错：What did you ate?  \n  对：What did you eat?\n\n### PracticeA（5）\n1. 配对不规则动词原形与过去式。  \n2. 填空：`She ___ (have) a cold yesterday.`  \n3. 改问句：`He saw a bird.`  \n4. 回答：`Did they buy books?`  \n5. 改错：`We didn\u0027t saw him.`\n\n### PracticeB（3）\n1. 采访同桌：昨天做了什么（3问3答）。  \n2. 用 `went/ate/saw` 各写1句。  \n3. 短文改错（4处）。\n\n### PracticeC（2）\n1. 记忆翻牌：20个不规则动词快配。  \n2. 写“上次春游”6句，至少3个不规则动词。\n\n### FunMission\n- 任务：记忆翻牌PK。限时记住并说出过去式。\n\n### ExitTicket\n1. `go` 的过去式是什么？  \n2. `Did he ___ (saw/see) it?`  \n3. `I didn\u0027t went.` 如何改？  \n- 自评徽章：`Time Traveler`\n\n---"
    },
    {
        "id":  "L12",
        "title":  "一般将来时",
        "markdown":  "### LessonMeta\n- 目标：掌握 be going to 与 will 的基础用法。\n- 预备知识：一般现在/过去时。\n- 学习产出：能表达计划与简单预测。\n\n### WarmupScene\n- 图：周末计划板（picnic, movie, homework）。\n- 对话：\n1. A: What are you going to do this weekend?  \n2. B: I am going to visit my grandparents.  \n3. A: Will it rain tomorrow?  \n4. B: I think it will.\n\n### RuleCard\n1. `be going to` 常表示已有计划。  \n2. `will` 常表示临时决定或预测。  \n3. 将来时间词：tomorrow, next week, soon。\n\n### TeacherTalk\n- 一般将来时用于表达尚未发生但计划发生或很可能发生的动作。\n- be going to 表示已有计划或安排，will 表示临时决定或预测。\n- 将来时间标志词：tomorrow, next week, soon, this weekend，出现时应优先考虑将来时。\n- will 后接动词原形，不可附加三单变化或其他变形。\n- 两种结构均属于将来时范畴，初学阶段先掌握基本用法，再逐步区分细微差别。\n- 口诀：计划常用 going to，临时决定常用 will。\n### PitfallBox\n- 错：I going to play football.  \n  对：I am going to play football.\n- 错：Will you to come?  \n  对：Will you come?\n\n### PracticeA（5）\n1. 填 be：`She ___ going to read.`  \n2. will/be going to 选择（5句）。  \n3. 改否定：`They will win.`  \n4. 改疑问：`You are going to swim.`  \n5. 改错：`He will goes home.`\n\n### PracticeB（3）\n1. 写3个周末计划句。  \n2. 预测明天天气2句。  \n3. 对话补全（8空）。\n\n### PracticeC（2）\n1. 设计“假期计划海报”英文文案（5句）。  \n2. 综合选择题（时态混合）。\n\n### FunMission\n- 任务：周末计划师。和同伴互相提问并做计划表。\n\n### ExitTicket\n1. `will` 后接动词什么形式？  \n2. `I ___ going to clean my room.`  \n3. `Will she plays...?` 如何改？  \n- 自评徽章：`Future Planner`\n\n---"
    },
    {
        "id":  "L13",
        "title":  "时态对比总练",
        "markdown":  "### LessonMeta\n- 目标：辨析一般现在、现在进行、一般过去、一般将来。\n- 预备知识：L08-L12。\n- 学习产出：能按时间线选择正确时态。\n\n### WarmupScene\n- 图：时光隧道（past-now-future）。\n- 对话：\n1. A: I play basketball every day.  \n2. B: I am playing now.  \n3. A: I played yesterday.  \n4. B: I will play tomorrow.\n\n### RuleCard\n1. 先看时间词，再选时态。  \n2. 进行时看“正在发生”；一般现在看“习惯事实”。  \n3. 过去与将来要注意动词形式变化。\n\n### TeacherTalk\n- 本课重点为四种时态的辨析与综合运用：一般现在时、现在进行时、一般过去时、一般将来时。\n- 判断步骤：先抓时间词，再判断动作性质（习惯/正在/过去/将来），最后确定动词形式。\n- 一般现在时对应习惯和事实，现在进行时对应正在发生的动作，一般过去时对应已结束的动作，一般将来时对应未来安排。\n- 多数时态错误源于混淆不同时间维度，而非单个知识点的遗忘。\n- 建议在脑中建立时间线模型，将四种时态可视化排列，有助于快速判断。\n- 口诀：先看时间，再看动作，再定时态。\n### PitfallBox\n- 错：Yesterday I play football.  \n  对：Yesterday I played football.\n- 错：Now he plays the piano.  \n  对：Now he is playing the piano.\n\n### PracticeA（5）\n1. 时间词配时态（5组）。  \n2. 动词正确形式填空（8空）。  \n3. 找出句子时态并标记。  \n4. 改错（4句）。  \n5. 快速分类：10句放入4种时态。\n\n### PracticeB（3）\n1. 写“昨天-今天-明天”各2句。  \n2. 阅读短文，完成时态选择。  \n3. 口头问答：老师给时间词，你造句。\n\n### PracticeC（2）\n1. 时光隧道挑战卷（10题综合）。  \n2. 写小段落《My Busy Weekend》（含3种时态）。\n\n### FunMission\n- 任务：时光隧道选择题闯关，答对解锁下一关。\n\n### ExitTicket\n1. `now` 常对应哪种时态？  \n2. `last week` 常对应哪种时态？  \n3. 写1句将来时。  \n- 自评徽章：`Tense Detective`\n\n---"
    },
    {
        "id":  "L14",
        "title":  "情态动词入门",
        "markdown":  "### LessonMeta\n- 目标：掌握 can/can\u0027t, must/mustn\u0027t, should 的基本语义。\n- 预备知识：基础句子结构。\n- 学习产出：能表达能力、规则与建议。\n\n### WarmupScene\n- 图：校园规则海报。\n- 对话：\n1. A: Can you swim?  \n2. B: Yes, I can.  \n3. A: Must we run in the hall?  \n4. B: No, we mustn\u0027t.\n\n### RuleCard\n1. `can` 表能力；`can\u0027t` 表不能。  \n2. `must` 表必须；`mustn\u0027t` 表禁止。  \n3. `should` 表建议，语气较温和。\n\n### TeacherTalk\n- 情态动词用于表达能力、义务、建议等语义，与普通动词功能不同。\n- can 表示能力，must 表示必须或禁止，should 表示建议，三者语义各有侧重。\n- 情态动词后接动词原形，不可加 -s、-ing 或 to。\n- 使用时应先判断语境：是描述能力、陈述规则，还是提出建议。\n- mustn't 表示禁止，语气强于 don't，常用于规则和命令场景。\n- 口诀：能用 can，必须用 must，建议用 should，后面动词回原形。\n### PitfallBox\n- 错：He can swims.  \n  对：He can swim.\n- 错：You mustn\u0027t to eat here.  \n  对：You mustn\u0027t eat here.\n\n### PracticeA（5）\n1. can/can\u0027t 填空（5句）。  \n2. must/mustn\u0027t 选词（校园规则）。  \n3. should 造句（健康建议）。  \n4. 改错：`She can sings.`  \n5. 回答：`Can you ride a bike?`\n\n### PracticeB（3）\n1. 写3条班级规则（must/mustn\u0027t）。  \n2. 给朋友3条建议（should）。  \n3. 对话补全（6空）。\n\n### PracticeC（2）\n1. 情景写作：`At the library`（4句）。  \n2. 抢答：听情景选情态动词。\n\n### FunMission\n- 任务：校园规则法官。判断行为是否合规并给出句子。\n\n### ExitTicket\n1. 情态动词后面动词用什么形式？  \n2. `You ___ be quiet in class.`  \n3. `He can to swim.` 如何改？  \n- 自评徽章：`Rule Keeper`\n\n---"
    },
    {
        "id":  "L15",
        "title":  "形容词与副词",
        "markdown":  "### LessonMeta\n- 目标：区分形容词和副词；掌握基础位置。\n- 预备知识：词类基础。\n- 学习产出：能正确修饰名词和动词。\n\n### WarmupScene\n- 图：运动会画面（fast runner, careful writer）。\n- 对话：\n1. A: She is a fast runner.  \n2. B: She runs fast.  \n3. A: He is a careful student.  \n4. B: He writes carefully.\n\n### RuleCard\n1. 形容词修饰名词：a beautiful flower。  \n2. 副词修饰动词：sing beautifully。  \n3. be动词后常接形容词：She is happy.\n\n### TeacherTalk\n- 形容词与副词均为修饰词，但修饰对象不同：形容词修饰名词，副词修饰动词。\n- be 动词后接形容词，不接副词。\n- 常见混淆对：good（形容词）/ well（副词），quick（形容词）/ quickly（副词）。\n- 判断方法：先确定修饰对象是名词还是动词，再选择对应词类。\n- 适当使用修饰词可增强句子的画面感和表达力。\n- 口诀：修饰名词用形容词，修饰动作用副词。\n### PitfallBox\n- 错：He is happily.  \n  对：He is happy.\n- 错：She sings beautiful.  \n  对：She sings beautifully.\n\n### PracticeA（5）\n1. 选形容词/副词（5句）。  \n2. 改写：`quick -\u003e quickly` 等。  \n3. 填空：`The boy is ___ (careful/carefully).`  \n4. 改错：`He runs quick.`  \n5. 用 be + 形容词写1句。\n\n### PracticeB（3）\n1. 看图写2句“形容词+名词”。  \n2. 写2句“动词+副词”。  \n3. 阅读短文圈出形容词和副词。\n\n### PracticeC（2）\n1. 美化句子挑战：把普通句加上合适形副。  \n2. 综合填空（8空）。\n\n### FunMission\n- 任务：描述力升级赛。给同一张图写“普通版”和“升级版”两段。\n\n### ExitTicket\n1. 哪类词修饰名词？  \n2. `She speaks ___ (good/well).`  \n3. `The soup tastes deliciously.` 如何改？  \n- 自评徽章：`Description Booster`\n\n---"
    },
    {
        "id":  "L16",
        "title":  "比较级与最高级",
        "markdown":  "### LessonMeta\n- 目标：掌握比较级、最高级及不规则变化。\n- 预备知识：形容词基础。\n- 学习产出：能比较两者与三者以上对象。\n\n### WarmupScene\n- 图：三名运动员成绩榜。\n- 对话：\n1. A: Tom is taller than Mike.  \n2. B: But Jack is the tallest.  \n3. A: Math is more difficult than English.  \n4. B: PE is the most exciting for me.\n\n### RuleCard\n1. 两者比较：`比较级 + than`。  \n2. 三者以上：`the + 最高级`。  \n3. 不规则：good-better-best, bad-worse-worst。\n\n### TeacherTalk\n- 比较级用于两者之间的比较，常用结构：比较级 + than。\n- 最高级用于三者或以上之间的比较，常用结构：the + 最高级。\n- 不规则变化需单独记忆：good-better-best, bad-worse-worst。\n- 部分形容词通过 more/most 构成比较级和最高级，通常为多音节词。\n- 使用前应先明确比较对象的数量：两者用比较级，三者以上用最高级。\n- 口诀：两者比较用比较级，三者以上用最高级。\n### PitfallBox\n- 错：He is more taller than me.  \n  对：He is taller than me.\n- 错：She is best in my class.  \n  对：She is the best in my class.\n\n### PracticeA（5）\n1. 写比较级/最高级：`small, big, happy`  \n2. 选词：better/best, more/most  \n3. 改错：`This book is difficulter.`  \n4. 填空：`My bag is ___ (heavy) than yours.`  \n5. 造句：`the tallest`。\n\n### PracticeB（3）\n1. 用班级数据写3个比较句。  \n2. 看图写1句最高级。  \n3. 完成短文（7空）。\n\n### PracticeC（2）\n1. 运动会数据比拼：根据表格写5句。  \n2. 纠错挑战（6句）。\n\n### FunMission\n- 任务：谁更强？抽角色卡，进行英语比较辩论。\n\n### ExitTicket\n1. 两者比较常用哪个词连接？  \n2. `good` 的最高级是什么？  \n3. `the most tall` 如何改？  \n- 自评徽章：`Comparison Coach`\n\n---"
    },
    {
        "id":  "L17",
        "title":  "介词定位课",
        "markdown":  "### LessonMeta\n- 目标：掌握地点介词与时间介词的基础用法。\n- 预备知识：there be 句型。\n- 学习产出：能准确描述位置和时间。\n\n### WarmupScene\n- 图：教室与日程表。\n- 对话：\n1. A: The cat is under the chair.  \n2. B: The clock is on the wall.  \n3. A: We have English at 8:00.  \n4. B: We have sports on Friday.\n\n### RuleCard\n1. 地点：in/on/under/behind/near/between。  \n2. 时间：`at` 时刻，`on` 具体某天，`in` 月份/年份。  \n3. 介词后接名词或名词短语。\n\n### TeacherTalk\n- 介词用于表达人、物、时间的位置或关系，是英语中的定位功能词。\n- 地点介词：in, on, under, behind, near, between。\n- 时间介词：at 用于具体时刻，on 用于具体某天，in 用于月份、年份及较长时段。\n- 地点介词与时间介词属两套系统，不可混用。\n- 解题建议：先在脑中构建空间或时间场景，再选择对应介词。\n- 口诀：时刻用 at，日期用 on，月份年份用 in。\n### PitfallBox\n- 错：in Monday  \n  对：on Monday\n- 错：at the morning  \n  对：in the morning\n\n### PracticeA（5）\n1. 图中位置填介词（5空）。  \n2. 时间介词选择（at/on/in）。  \n3. 改错：`The ball is in the desk.`  \n4. 完成句子：`My birthday is ___ July.`  \n5. 写1句 between 句。\n\n### PracticeB（3）\n1. 描述你的房间3句。  \n2. 写一周课程表句子3句。  \n3. 对话填空（地点+时间介词）。\n\n### PracticeC（2）\n1. 地图导航任务：根据指令写路线句。  \n2. 介词纠错短文（5处）。\n\n### FunMission\n- 任务：地图导航员。用英语指导同学从校门走到图书馆。\n\n### ExitTicket\n1. `___ 7:30` 用哪个介词？  \n2. `___ Sunday` 用哪个介词？  \n3. `The bag is on the box.` 画出位置关系。  \n- 自评徽章：`Location Navigator`\n\n---"
    },
    {
        "id":  "L18",
        "title":  "疑问句全家桶",
        "markdown":  "### LessonMeta\n- 目标：掌握一般疑问句和特殊疑问句提问框架。\n- 预备知识：be/do/does/did/will 基础。\n- 学习产出：能提出并回答完整问题。\n\n### WarmupScene\n- 图：校园采访现场。\n- 对话：\n1. A: Do you like science?  \n2. B: Yes, I do.  \n3. A: Where do you have lunch?  \n4. B: We have lunch in the canteen.\n\n### RuleCard\n1. 一般疑问句：be/do/does/did/will 提前。  \n2. 特殊疑问句：`疑问词 + 一般疑问句结构`。  \n3. 回答要完整，不只说单词。\n\n### TeacherTalk\n- 疑问句分为一般疑问句和特殊疑问句两类，结构各有规则。\n- 一般疑问句：将助动词（be/do/does/did/will）提至句首。\n- 特殊疑问句：疑问词（What/Where/When/How）+ 一般疑问句结构。\n- 回答应使用完整句子，避免仅用单词应答。\n- 训练重点为双向能力：既能提问，也能完整回答。\n- 口诀：先看是一般问还是特殊问，再选对结构。\n### PitfallBox\n- 错：Where you go?  \n  对：Where do you go?\n- 错：Do she like music?  \n  对：Does she like music?\n\n### PracticeA（5）\n1. 陈述句改一般疑问句（3句）。  \n2. 用 what/where/when/how 填空。  \n3. 配对问答（4组）。  \n4. 改错：`What does he does?`  \n5. 写完整回答：`Do you... ?`\n\n### PracticeB（3）\n1. 设计采访提纲（5个问题）。  \n2. 同伴互访并记录答案。  \n3. 将答案整理成3句报告。\n\n### PracticeC（2）\n1. 疑问句闯关卷（10题）。  \n2. 看图生成“5W1H”问题各1个。\n\n### FunMission\n- 任务：采访小记者。采访3名同学并做英语播报。\n\n### ExitTicket\n1. 特殊疑问句的结构核心是什么？  \n2. `___ do you go to bed?`  \n3. `Where does he goes?` 如何改？  \n- 自评徽章：`Question Master`\n\n---"
    },
    {
        "id":  "L19",
        "title":  "连接词与复合句",
        "markdown":  "### LessonMeta\n- 目标：掌握 and/but/because/so/if 的基础连接功能。\n- 预备知识：简单句写作。\n- 学习产出：能写有逻辑关系的复合句。\n\n### WarmupScene\n- 图：故事四格漫画。\n- 对话：\n1. A: I was tired, so I went to bed early.  \n2. B: I wanted to play, but it rained.  \n3. A: I stayed at home because I had homework.  \n4. B: If it is sunny tomorrow, we will fly kites.\n\n### RuleCard\n1. `and` 并列；`but` 转折。  \n2. `because` 原因；`so` 结果。  \n3. `if` 引导条件（小学阶段先掌握基础条件表达）。\n\n### TeacherTalk\n- 连接词用于将简单句组合为复合句，建立句子间的逻辑关系。\n- and 表示并列，but 表示转折，because 表示原因，so 表示结果，if 表示条件。\n- because 与 so 不可在同一句中同时使用，否则造成逻辑重复。\n- 书写故事时，应确保前后句之间的逻辑关系合理通顺。\n- 掌握连接词是提升英语逻辑表达能力的关键步骤。\n- 口诀：并列 and，转折 but，原因 because，结果 so，条件 if。\n### PitfallBox\n- 错：Because I was late, so I ran fast.  \n  对：I was late, so I ran fast. / Because I was late, I ran fast.\n- 错：If it will rain, we stay home.  \n  对：If it rains, we will stay home.（小学阶段可先记固定搭配）\n\n### PracticeA（5）\n1. 选择连接词填空（5句）。  \n2. 合并短句（3组）。  \n3. 改错：`I like apples but I don\u0027t like bananas and.`  \n4. because/so 互换改写。  \n5. 写1句 if 句。\n\n### PracticeB（3）\n1. 用4个连接词各写1句。  \n2. 补全故事（8空）。  \n3. 判断逻辑是否合理并修改。\n\n### PracticeC（2）\n1. 故事接龙：每人用1个连接词续写。  \n2. 写一段“放学后”微故事（5句，含3种连接词）。\n\n### FunMission\n- 任务：故事接龙工坊。抽取“人物+地点+事件”卡，完成连贯故事。\n\n### ExitTicket\n1. 表示原因常用哪个连接词？  \n2. 表示转折常用哪个连接词？  \n3. 写1句含 `if` 的句子。  \n- 自评徽章：`Logic Linker`\n\n---"
    },
    {
        "id":  "L20",
        "title":  "语法大冒险复盘",
        "markdown":  "### LessonMeta\n- 目标：整合20课语法点，完成综合任务并归因错题。\n- 预备知识：L01-L19。\n- 学习产出：能在语篇中综合使用语法并自我纠错。\n\n### WarmupScene\n- 图：密室通关地图，4道门分别对应词法、句法、时态、逻辑。\n- 对话：\n1. A: We need all grammar keys to open the final door.  \n2. B: Let’s check nouns, tenses and questions first.  \n3. A: I found an error in this sentence.  \n4. B: Great! You are a grammar hero.\n\n### RuleCard\n1. 综合做题顺序：先读语境 -\u003e 找时间词 -\u003e 看主语 -\u003e 定动词形式。  \n2. 检查清单：大小写、标点、主谓一致、时态一致。  \n3. 改错要说明“为什么错”，不是只改答案。\n\n### TeacherTalk\n- 本课为综合复盘，将前 19 课的语法知识整合运用。\n- 做综合题的步骤：先读语境，找时间词，看主语，定动词形式。\n- 自查清单涵盖：大小写、标点、主谓一致、时态一致、词形变化。\n- 改错时应说明错误原因，而非仅提供正确答案。\n- 综合运用的难点在于多知识点同时出现时的准确判断。\n- 口诀：先看语境，再看时间，再看主语，最后检查形式。\n### PitfallBox\n- 错：Yesterday he goes to school and is happy.  \n  对：Yesterday he went to school and was happy.\n- 错：She can sings very well because she practice every day.  \n  对：She can sing very well because she practices every day.\n\n### PracticeA（5）\n1. 全语法选择题（10题）。  \n2. 句型转换（6题）。  \n3. 名词/代词/冠词混合填空（8空）。  \n4. 时态综合填空（8空）。  \n5. 连词逻辑判断（4题）。\n\n### PracticeB（3）\n1. 阅读短文改错（8处）。  \n2. 看图写作：我的周末（6句，含2种时态）。  \n3. 采访问答：3问3答，覆盖疑问句。\n\n### PracticeC（2）\n1. 密室通关总挑战（分关卡积分）。  \n2. 错因归类表：`时态错误/词形错误/结构错误/逻辑错误`。\n\n### FunMission\n- 任务：密室通关总挑战。四人小组分工：读题官、规则官、改错官、汇报官。\n\n### ExitTicket\n1. 今天你最容易错的是哪类？  \n2. 写1句你最满意的英语句子。  \n3. 给自己下阶段目标（1条）。  \n- 自评徽章：`Grammar Hero`"
    }
];

